/* Generated by build_lessons.py; authored positions, not historical games. */
globalThis.CaptureLessons = [
  {
    "id": "defender-white",
    "skill": "defense",
    "title": "The offered rook",
    "fen": "4r1k1/5ppp/8/8/r7/8/5PPP/3Q2K1 w - - 0 1",
    "take": false,
    "prompt": "Your queen can take the rook on a4. Would you accept?",
    "question": "After Qxa4, which reply must you notice?",
    "options": [
      "Re1#: the rook reaches the back rank.",
      "h6: Black makes a pawn move.",
      "Kf8: Black moves the king."
    ],
    "answer": 0,
    "hint": "Your queen has a defensive job on the first rank. What happens when it leaves?",
    "explanation": "Qxa4 wins a rook but removes the queen from d1. Black plays Re1 checkmate. The pawns block the king from escaping. The immediate mate outweighs the material gain.",
    "takeaway": "Before moving a defender, name the square or line it protects.",
    "side": "White",
    "frames": [
      "4r1k1/5ppp/8/8/r7/8/5PPP/3Q2K1 w - - 0 1",
      "4r1k1/5ppp/8/8/Q7/8/5PPP/6K1 b - - 0 1",
      "6k1/5ppp/8/8/Q7/8/5PPP/4r1K1 w - - 1 2"
    ],
    "moves": [
      {
        "uci": "d1a4",
        "san": "Qxa4"
      },
      {
        "uci": "e8e1",
        "san": "Re1#"
      }
    ]
  },
  {
    "id": "defender-black",
    "skill": "defense",
    "title": "The offered rook (Black to move)",
    "fen": "3q2k1/5ppp/8/R7/8/8/5PPP/4R1K1 b - - 0 1",
    "take": false,
    "prompt": "Your queen can take the rook on a5. Would you accept?",
    "question": "After Qxa5, which reply must you notice?",
    "options": [
      "Re8#: the rook reaches the back rank.",
      "h3: White makes a pawn move.",
      "Kf1: White moves the king."
    ],
    "answer": 0,
    "hint": "Your queen has a defensive job on the eighth rank. What happens when it leaves?",
    "explanation": "Qxa5 wins a rook but removes the queen from d8. White plays Re8 checkmate. The pawns block your king from escaping. The immediate mate outweighs the material gain.",
    "takeaway": "Before moving a defender, name the square or line it protects.",
    "side": "Black",
    "frames": [
      "3q2k1/5ppp/8/R7/8/8/5PPP/4R1K1 b - - 0 1",
      "6k1/5ppp/8/q7/8/8/5PPP/4R1K1 w - - 0 2",
      "4R1k1/5ppp/8/q7/8/8/5PPP/6K1 b - - 1 2"
    ],
    "moves": [
      {
        "uci": "d8a5",
        "san": "Qxa5"
      },
      {
        "uci": "e1e8",
        "san": "Re8#"
      }
    ]
  },
  {
    "id": "recapture-white",
    "skill": "count",
    "title": "The pawn on the open file",
    "fen": "3r2k1/5ppp/8/3p4/8/8/5PPP/3Q2K1 w - - 0 1",
    "take": false,
    "prompt": "Your queen can take the pawn on d5. Would you accept?",
    "question": "After Qxd5 Rxd5, what did the capturing side gain or lose?",
    "options": [
      "Gained 1 point.",
      "Lost 8 points: queen for pawn.",
      "An equal exchange."
    ],
    "answer": 1,
    "hint": "Follow the d-file beyond the pawn. Count both captures: pawn = 1, queen = 9.",
    "explanation": "The first capture wins a pawn, but the rook then takes the queen. That is 1 gained and 9 lost: a net loss of 8 material points. This lesson only needs the immediate recapture.",
    "takeaway": "Count the complete visible exchange, not just its first move.",
    "side": "White",
    "frames": [
      "3r2k1/5ppp/8/3p4/8/8/5PPP/3Q2K1 w - - 0 1",
      "3r2k1/5ppp/8/3Q4/8/8/5PPP/6K1 b - - 0 1",
      "6k1/5ppp/8/3r4/8/8/5PPP/6K1 w - - 0 2"
    ],
    "moves": [
      {
        "uci": "d1d5",
        "san": "Qxd5"
      },
      {
        "uci": "d8d5",
        "san": "Rxd5"
      }
    ]
  },
  {
    "id": "recapture-black",
    "skill": "count",
    "title": "The pawn on the open file (Black to move)",
    "fen": "3q2k1/5ppp/8/8/3P4/8/5PPP/3R2K1 b - - 0 1",
    "take": false,
    "prompt": "Your queen can take the pawn on d4. Would you accept?",
    "question": "After Qxd4 Rxd4, what did the capturing side gain or lose?",
    "options": [
      "Gained 1 point.",
      "Lost 8 points: queen for pawn.",
      "An equal exchange."
    ],
    "answer": 1,
    "hint": "Follow the d-file beyond the pawn. Count both captures: pawn = 1, queen = 9.",
    "explanation": "The first capture wins a pawn, but the rook then takes the queen. That is 1 gained and 9 lost: a net loss of 8 material points. This lesson only needs the immediate recapture.",
    "takeaway": "Count the complete visible exchange, not just its first move.",
    "side": "Black",
    "frames": [
      "3q2k1/5ppp/8/8/3P4/8/5PPP/3R2K1 b - - 0 1",
      "6k1/5ppp/8/8/3q4/8/5PPP/3R2K1 w - - 0 2",
      "6k1/5ppp/8/8/3R4/8/5PPP/6K1 b - - 0 2"
    ],
    "moves": [
      {
        "uci": "d8d4",
        "san": "Qxd4"
      },
      {
        "uci": "d1d4",
        "san": "Rxd4"
      }
    ]
  },
  {
    "id": "free-white",
    "skill": "reply",
    "title": "The bishop in the center",
    "fen": "6k1/5ppp/8/4b3/8/8/5PPP/4R1K1 w - - 0 1",
    "take": true,
    "prompt": "Your rook can take the bishop on e5. Would you accept?",
    "question": "After Rxe5, which description fits Black's immediate legal replies?",
    "options": [
      "Black can recapture the rook immediately.",
      "Black has mate in one.",
      "Black has no check or capture; you won a bishop."
    ],
    "answer": 2,
    "hint": "Check every black piece, including the king and pawns. What could take e5 or check your king?",
    "explanation": "Rxe5 wins the undefended bishop. Black has no immediate legal check or capture. The replay shows h6 as one quiet reply, not a uniquely best move. For this short-horizon exercise, accept the bishop.",
    "takeaway": "When no concrete immediate refutation appears, do not invent a trap.",
    "side": "White",
    "frames": [
      "6k1/5ppp/8/4b3/8/8/5PPP/4R1K1 w - - 0 1",
      "6k1/5ppp/8/4R3/8/8/5PPP/6K1 b - - 0 1",
      "6k1/5pp1/7p/4R3/8/8/5PPP/6K1 w - - 0 2"
    ],
    "moves": [
      {
        "uci": "e1e5",
        "san": "Rxe5"
      },
      {
        "uci": "h7h6",
        "san": "h6"
      }
    ]
  },
  {
    "id": "free-black",
    "skill": "reply",
    "title": "The bishop in the center (Black to move)",
    "fen": "4r1k1/5ppp/8/8/4B3/8/5PPP/6K1 b - - 0 1",
    "take": true,
    "prompt": "Your rook can take the bishop on e4. Would you accept?",
    "question": "After Rxe4, which description fits White's immediate legal replies?",
    "options": [
      "White can recapture the rook immediately.",
      "White has mate in one.",
      "White has no check or capture; you won a bishop."
    ],
    "answer": 2,
    "hint": "Check every white piece, including the king and pawns. What could take e4 or check your king?",
    "explanation": "Rxe4 wins the undefended bishop. White has no immediate legal check or capture. The replay shows h3 as one quiet reply, not a uniquely best move. For this short-horizon exercise, accept the bishop.",
    "takeaway": "When no concrete immediate refutation appears, do not invent a trap.",
    "side": "Black",
    "frames": [
      "4r1k1/5ppp/8/8/4B3/8/5PPP/6K1 b - - 0 1",
      "6k1/5ppp/8/8/4r3/8/5PPP/6K1 w - - 0 2",
      "6k1/5ppp/8/8/4r3/7P/5PP1/6K1 b - - 0 2"
    ],
    "moves": [
      {
        "uci": "e8e4",
        "san": "Rxe4"
      },
      {
        "uci": "h2h3",
        "san": "h3"
      }
    ]
  }
];
