from pathlib import Path
import os,json,re,hashlib,shutil,subprocess,zipfile
import numpy as np,pandas as pd
from scipy.stats import spearmanr
from sklearn.model_selection import GroupKFold
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
B=Path(__file__).resolve().parent;F=B/'figures';F.mkdir(exist_ok=True)
DATA=Path(os.environ.get('VIRTUAL_BODY_CRISPR_DATA',str(B/'data/doench2016.csv' if (B/'data/doench2016.csv').exists() else Path.home()/'.cache/crispr_autoresearch/doench2016.csv')))
assert hashlib.sha256(DATA.read_bytes()).hexdigest()=='97a4fda9481985d5e4ea6b18bb52e17b1c953913fbb901f56a134ec3c31f2972'
df=pd.read_csv(DATA).dropna(subset=['30mer','score_drug_gene_rank','Target gene']);df=df[df['30mer'].str.fullmatch('[ACGT]{30}')].reset_index(drop=True)
r=json.loads((B/'data/crispr-benchmark.json').read_text());sim=json.loads((B/'data/results.json').read_text());ext=json.loads((B/'data/extinction-feasibility.json').read_text());nested=json.loads((B/'data/nested-cell-checks.json').read_text())
assert len(df)==5310
OOF={p:pd.read_csv(B/f'data/crispr-{p}-oof.csv') for p in ['sequence_disjoint','gene_disjoint']}
for p,a in OOF.items():assert np.allclose(a.observed_rank,df.score_drug_gene_rank)
plt.rcParams.update({'font.size':8,'axes.titlesize':9,'axes.labelsize':8,'figure.facecolor':'white','savefig.facecolor':'white'})
colors=['#0072b2','#e69f00','#009e73','#cc79a7'];models=['onehot_ridge','existing_sequence_features_ridge','hrl_sequence_graph'];names=['One-hot Ridge','Sequence features + Ridge','Sequence features + HRL']
figcount=0

def save(fig,name):
 global figcount
 fig.savefig(F/f'{name}.pdf',bbox_inches='tight');fig.savefig(F/f'{name}.png',dpi=180,bbox_inches='tight');plt.close(fig);figcount+=1

def p(title,body,figure=None,caption='',table=None,equation=None,kind='Argument'):
 pages.append(dict(title=title,body=body,figure=figure,caption=caption,table=table,equation=equation,kind=kind))
pages=[]
# A conceptual overview, carefully separated from a biological result.
fig,ax=plt.subplots(figsize=(8.4,2.4));ax.axis('off')
labels=['Molecular\nnetworks','Cell\nstates','Spatial\nniches','Tissues\nand organs','Whole-body\nconstraints']
for i,label in enumerate(labels):
 ax.text(i,0,label,ha='center',va='center',bbox=dict(boxstyle='round,pad=.6',fc=colors[i%4],ec='none'),color='white',fontsize=10)
 if i<4:ax.annotate('',xy=(i+.7,0),xytext=(i+.3,0),arrowprops=dict(arrowstyle='<->',lw=2,color='#243746'))
ax.set(xlim=(-.6,4.6),ylim=(-.7,.7));save(fig,'architecture')
p('To Cure Cancer: The Virtual Body',[
'I want to cure cancer. That is the purpose of this work, and I intend to say it plainly. I want a model that follows the cell into the niche, the niche into the tissue, the tissue into the organ, and the organ into the person. I want the cell of cells to become an executable account of what changes, what resists, what repairs, and what survives.',
'My algorithms begin with objects, labels and relationships. They become useful when those objects acquire measured identities and those relationships acquire testable consequences. Hierarchical relaxation gives me a language for the traffic between levels. The body gives that language its obligations: preserve healthy function, confront malignant growth, and expose the assumptions that decide which is which.',
'This dissertation puts my ambition beside the calculations actually executed. It contains measured assay data, held-out predictions, repaired nested-cell code, a multiscale dynamical prototype and a local-stability analysis. Each has its own evidentiary role. I insist that the reader be able to tell them apart, reproduce the numbers and challenge the conclusions.',
'Reality retains veto power. I keep the ambition; I also keep the ledger. The following eighty pages are the first fully assembled computational dissertation for this programme: argument, mathematics, implementation, measurements and case-by-case audit.'],figure='architecture',caption='Conceptual research architecture. Arrows indicate intended cross-scale information exchange; the complete biological coupling is a research objective.',kind='Title and author statement')
p('Abstract: ambition, execution and evidence',[
'I develop a virtual-body research programme around hierarchical relaxation labeling, explicit observation models, nested categorical state and organism-level constraints. The motivating objective is cancer control that preserves the person. The executed contribution is narrower and inspectable: a measured CRISPR assay-rank benchmark, a repaired nested-state implementation, and a synthetic three-site tumor-body model with a formal constant-exposure stability calculation.',
'The measured table contains 5,310 rows, 4,379 distinct sequences and 17 target genes. A historical row-random split shares 271 distinct test sequences with training. I therefore report fixed five-fold sequence-disjoint and gene-disjoint evaluations. All annotation, drug/gene identity and precomputed stacking columns are removed. The sequence-only feature extraction is checked against the original implementation, and held-out assay labels never enter the relaxation prior.',
'On sequence-disjoint evaluation, pooled out-of-fold Spearman correlations are 0.395318 for one-hot Ridge, 0.479858 for the existing sequence-feature Ridge model and 0.480544 for its HRL extension. Gene-disjoint values are 0.388453, 0.400323 and 0.403291. These small differences are descriptive point estimates; this dissertation does not establish statistical superiority or a treatment effect.',
'An audited virtual-cell snapshot corrects a missing method, entropy normalization, state-change measurement and ambiguous abstention coding. A seven-node, three-level hierarchy passes ten recursive steps. In the synthetic body model, a resistant-clone invasion threshold of 5.181195 dimensionless exposure exceeds the 0.136364 limit implied by an assumed reserve floor of 0.7. No constant-exposure intersection exists in the nominal model or its 24 sampled configurations.',
'The dissertation establishes executable components and reproducible calculations. It does not establish a cancer cure, a calibrated virtual human or clinical safety. I make that boundary explicit because a programme directed toward a cure must remain answerable to biological outcomes.'],table=[['Evidence class','Executed object'],['Measured','Assay ranks and held-out predictions'],['Numerical','Three-site trajectories and sensitivity'],['Formal','Local stability of specified equations'],['Software','Nested-state repairs and checks']],kind='Abstract')
p('How to read this dissertation',[
'I organize the record so that every broad claim can be walked back to its narrowest supporting calculation. The opening chapters establish the language of the virtual body, the inference mechanism, the observation problem and the dynamical assumptions. The result chapters then expose individual folds, model behavior, every gene represented in the measured table, every nominal control and every sampled parameter configuration.',
'The page structure is deliberate. A result page names its denominator, distinguishes measured from synthetic quantities, and gives a figure or table that can be regenerated from the supplied files. The case reports are part of the audit: they prevent an average from concealing a difficult fold, a small gene group, a toxic model assumption or a resistant residual population.',
'Measured assay-rank predictions occupy a different layer from synthetic treatment trajectories. A gene name in the assay table identifies a prediction context; it does not prescribe a cancer therapy. Likewise, a favorable simulated trajectory records a consequence of assumed coefficients. It does not establish that a drug, dose or intervention has the corresponding effect in a person.',
'I use first-person argument throughout because the research purpose is mine. The figures, numerical summaries and inferential boundaries remain inspectable regardless of who speaks. This is an independent research dissertation developed with Codex assistance; no university degree, journal acceptance or external experimental validation is claimed.'],table=[['Pages','Content'],['1-3','Purpose, abstract and reading map'],['4-19','Theory, methods, proofs and reproducibility'],['20-29','Ten held-out fold reports'],['30-35','Six model/protocol diagnostics'],['36-52','Seventeen gene-context reports'],['53-56','Four synthetic control trajectories'],['57-80','Twenty-four parameter-case reports']],kind='Reader guide')
core=[
('The objective: preserve the person',[
'I take curing cancer as the organizing objective, rather than an excuse to reduce the body to a single score. Tumor burden belongs in the objective. So do resistant populations, healthy reserve, immune competence, function and the time over which control persists. A model that suppresses one population while destroying the system around it has answered the wrong question.',
'The useful mathematical object is a constrained intervention problem. Let the latent body state be x, the intervention history be u and the measured outcomes be y. I seek policies whose expected outcomes improve specified cancer endpoints while respecting explicit safety constraints. Those endpoints must be defined for a cancer context and a time horizon. Their meaning cannot be supplied by an attractive animation or a small floating-point value.',
'A cancer programme also needs a definition of recurrence and a record of follow-up. Tumor-free local stability, transient suppression, undetectable burden and clinical cure are different predicates. The executed model analyzes one of those predicates: local stability of a specified equilibrium under constant exposure. The measured benchmark evaluates another: prediction of assay response ranks. Neither predicate becomes a clinical cure merely because I combine them in one document.',
'I want the hierarchy because errors can cross it. An intracellular change can alter population selection. Selection can reshape the niche. The niche can alter transport and immune access. Organ-level injury can constrain exposure. A serious virtual body must make such feedback visible while distinguishing measured couplings from placeholders.',
'The immediate design discipline is therefore to specify the prediction, the observation and the permitted inference together. The larger ambition remains present in every calculation. It gives the work direction; the evidence gives each completed result its scope. I will not improve that evidence by changing the name of the result.'],None,None),
('An evidence ledger for the cell of cells',[
'I carry four epistemic questions into the model: what is observed, what is resolved, what is missing, and what conflicts with the current account? The Manuelian known-known and unknown distinctions help me keep those questions separate. They are metadata about knowledge, not extra biological substances. A missing assay, an uncertain cell identity and an untested causal link should not share one undifferentiated confidence number.',
'For an empirical edge I record a source, context, direction, sign, units, uncertainty and validation status. For an assumed edge I record the assumption and the calculation it enables. For a learned coefficient I record the training partition and the procedure that estimated it. For a formal proposition I record the hypotheses and the proof. This ledger makes the model a collection of accountable commitments rather than a collection of impressive names.',
'The drive audit matters to this discipline. It enumerated 880,934 accessible files and searched 45,884 selected text/code files. It found the existing HRL2026 implementation, the measured CRISPR table and a local virtual-cell perspective. It also found medical-imaging examples and cancer-related terms in private sleep-study metadata. Those findings have different scientific relevance. I did not repurpose private physiological records as treatment-response observations.',
'Coverage also has limits: protected directories, archives and most binary files were not decoded, and the inventory recorded 35 traversal or stat errors. I state those limits beside the count. A search record should help another researcher locate the evidence; it should not imply that every physical byte has been read or every possible dataset has been ruled out.',
'The public bundle includes the calculations and their provenance. The raw private inventory remains local. This separation protects the audit from becoming a disclosure of unrelated records, while keeping the actual supporting data products available for inspection.'],None,None),
('The hierarchy has physical obligations',[
'I use cells of cells as a name for organization across scales. Molecules participate in cellular processes; cells form niches and tissues; organs interact within the organism. The phrase does not mean that every organ is literally a cell nested inside another cell. Its mathematical value lies in typed aggregation, projection and feedback.',
'An aggregation map can summarize lower-level states into an organ-level quantity. A projection map can distribute a shared constraint back to the components that experience it. Both require semantics. A sum of cell counts, a mean of label strengths and a flux across a vascular boundary are different operations. Their units and conservation laws differ, and the hierarchy must preserve those differences.',
'The existing nested categorical implementation supplies recursion and state distributions. It does not yet supply measured bidirectional signaling between physical cells. The three-site dynamical prototype supplies shared exposure, aggregate tumor transport, resource dynamics and tissue reserve. It does not resolve individual cell mechanics or molecular kinetics. I treat those implementations as distinct modules with distinct interfaces.',
'A future connection must identify what is exchanged. A probability-like label strength may inform a kinetic regime only after a state-to-rate map is fitted and validated. A tissue exposure may alter a cell model only through a physically meaningful input. Copying the same signal into several levels without accounting for it can double-count evidence or violate balance.',
'I therefore require typed ports: measured state, inferred state, conserved quantity, control signal and uncertainty annotation. The architecture becomes stronger when those types are explicit. The ambition is a body model in which an apparent local success can be followed through the system until its organism-level consequence is visible.'],None,'architecture'),
('Observation comes before interpretation',[
'A latent cell state is useful only if I can say what an instrument would observe when that state changes. I write an observation model for assay ranks, counts, images or biochemical measurements instead of pretending that one convenient representation measures all of them. Measurement noise, censoring, batch effects and missing values belong in that model.',
'The current measured dataset supplies normalized assay response ranks. The benchmark predicts those ranks from sequence features. It does not observe a complete intracellular state, a spatial tumor neighborhood or a whole-body outcome. Percent Peptide and amino-acid cut position are annotations in the source table; they are not the response variable used in this dissertation. The appended annotation features are excluded from the new benchmark.',
'An observation likelihood makes the distinction precise. If z is a latent state and y is an observation, the model must specify how y depends on z and on the assay context. A classifier score is not automatically that likelihood. A normalized vector produced by relaxation is not automatically a calibrated posterior. Calibration is an additional empirical question.',
'Identifiability follows immediately. Several different latent mechanisms can produce the same observed rank. A single cross-sectional assay cannot generally identify growth, death, migration, exposure clearance and immune recruitment simultaneously. Longitudinal observations and controlled perturbations are needed to separate competing explanations. Otherwise a fitted mechanism can be merely one of many compatible stories.',
'My rule is to let each instrument define what it can discriminate. I can build a hierarchy of hypotheses around that discrimination. I cannot enlarge the instrument by renaming its output. The measured result remains valuable when its limits are named.'],r'y \sim p(y\mid z, a, b),\qquad z\sim p(z\mid \theta).',None),
('Sparse factors: relations become executable',[
'My relaxation engine works with objects and label distributions. A factor associates a small set of objects with a compatibility tensor. Pairwise factors contract that tensor against the other object\'s current distribution. Three-way factors contract against two distributions. The resulting support changes the relative strength of competing labels.',
'This is an economical way to express relational hypotheses. It avoids allocating a dense tensor over every possible object pair. It also makes each proposed relation inspectable: which objects participate, which labels are compatible, and what sign the contribution carries. Rosenfeld, Hummel and Zucker developed the classical relaxation formulation; Hummel and Zucker analyzed its foundations. My present sparse implementation extends the software interface around that tradition [1,2].',
'A higher-order factor is meaningful when the biological hypothesis is genuinely joint. An immune, tumor and stromal interaction may depend on a configuration that cannot be represented by one isolated pairwise effect. That possibility does not establish that a chosen tensor is biologically correct. The tensor must be derived from measurements, justified assumptions or an identified learned model.',
'The measured CRISPR extension in this dissertation uses pairwise sequence-similarity factors. The earlier synthetic annotation demo also uses three-way homophily factors, correct by construction in its synthetic patches. I keep those two experiments separate. The real-data benchmark does not establish the value of three-way biological factors, because it does not test them.',
'Sparsity is therefore a computational property, while validity is an evidentiary property. I want both. The first makes the experiment affordable; the second makes it worth doing. A compact graph can still encode a mistaken relation, and a converged field can still be wrong.'],r'q_i(\ell)=\sum_{f\ni i}\sum_{\ell_{-i}} C_f(\ell,\ell_{-i})\prod_{j\in f\setminus i}s_j(\ell_j).',None),
('The update and its actual guarantees',[
'The generic engine preserves an explicit prior in each multiplicative update. Let pi be the initial label distribution, s the current distribution, rho the prior-strength parameter and q the normalized support. The update multiplies a prior/current-state base by a nonnegative support modulation, then normalizes each row.',
'If all base weights are nonnegative and at least one updated weight is positive, normalization produces a nonnegative row with unit total. That is a simplex-preservation statement. It does not establish global optimization, calibrated probability, biological truth or uniqueness of the limiting state. Those are separate questions. I do not infer them from row sums.',
'The implementation rescales support within a row. That changes how compatibility magnitudes influence the result. A global rescaling of all contributions can be partly removed by min-max normalization, while mixtures of factors and prior strength still change the field. Parameters should therefore be interpreted through the implemented transformation rather than through the raw tensor alone.',
'Convergence is measured by a maximum change in the state field. All ten measured-data HRL fits reach the specified tolerance within the iteration cap. This is an execution result: the update stabilizes on those inputs. The small predictive gains are assessed separately through held-out assay ranks. Stable arithmetic and useful prediction are related achievements, not identical achievements.',
'I keep iteration counts and the convergence flag in the run record. If a future field oscillates or reaches the cap, that must appear beside its predictive result. A terminating condition should identify what has terminated. It should never silently promote numerical stillness into a conclusion about the body.'],r's_i^{+}(\ell)=\frac{\pi_i(\ell)^\rho s_i(\ell)^{1-\rho}[1+\eta\widehat q_i(\ell)]}{\sum_m\pi_i(m)^\rho s_i(m)^{1-\rho}[1+\eta\widehat q_i(m)]}.',None),
('Unknown is an output with a meaning',[
'I want the model to retain the ability to say that its available labels do not settle an object. The generic engine offers a rejection label; the nested implementation also needs a distinct abstention code. That distinction is computationally small and conceptually important. A certain negative category and an uncertain object must not be returned as the same integer.',
'The original projection method used minus one both for a certain negative trit and for uncertainty. The audited snapshot uses minus two for abstention. This repair does not decide when abstention is biologically appropriate. It makes the interface capable of representing the decision without ambiguity. A downstream consumer can now distinguish the states.',
'The rejection mechanism itself requires evaluation. A system that rejects every difficult cell may achieve good accuracy on what remains while providing poor coverage. A system that never rejects may provide confident-looking mistakes. Coverage, error among accepted cases and the composition of rejected cases should be reported together. The synthetic rejection demonstration records twelve rejected objects; it does not calibrate those decisions on real cells.',
'Entropy is another observable, not a substitute for uncertainty validation. A normalized categorical vector has a well-defined Shannon entropy. An arbitrary three-element weight vector must be normalized before that definition applies. The snapshot enforces this condition and rejects invalid weights. Biological uncertainty includes missing mechanisms and domain shift that categorical entropy alone cannot capture.',
'My aim is an honest interface between available evidence and unresolved state. The unknown category becomes useful when it triggers a traceable question: which measurement, context or model discrepancy would resolve this case? It becomes decoration when it merely supplies another color.'],r'H(p)=-\frac{1}{\log 3}\sum_{k:p_k>0}p_k\log p_k,\quad p_k\geq0,\quad\sum_kp_k=1.',None),
('The measured assay table and its provenance',[
'The useful measured resource was already on the drive: the cached Doench/Azimuth table used by the existing CRISPR prediction project. Its supplied response is score_drug_gene_rank, normalized within drug/gene contexts. The source paper concerns guide design and activity prediction [3]. I use it as an assay-prediction benchmark, not as a catalogue of clinical cancer treatments.',
'There are 5,310 retained rows and 4,379 distinct sequences across seventeen target genes. Repeated sequences occur across the table, including distinct assay contexts. That structure makes a row-random split a poor way to assert independence of sequence-based predictions. It also means that a sequence-only model cannot represent every context-specific difference in response.',
'The historical prediction code includes annotation and drug/gene lookup features, and a precomputed predictions field. I remove all twenty-five appended columns in the new calculation. The remaining 968 features are derived from sequence alone. The portable extraction reproduces those columns exactly on every retained row, and an executable perturbation of the metadata providers leaves them unchanged.',
'The source file is identified by SHA-256 in the reproducibility record. The public dissertation bundle contains source-row identifiers, observed response ranks, held-out predictions and the derived figures. It does not contain private sleep-study records, a raw drive inventory or a proposed therapeutic guide-selection protocol.',
'The denominator is therefore explicit. This table can test whether the implemented predictor orders the supplied assay ranks on its partitions. It cannot by itself establish tumor selectivity, delivery, organism toxicity, durability of cancer control or benefit in a patient. I retain the data because it provides a measured bridge into biological prediction, with those boundaries intact.'],None,None),
('Holdouts, overlap and the meaning of a test',[
'I found 271 distinct test sequences that also occur in the historical training set, among 1,034 distinct test sequences. This does not prove that every previous prediction was memorized. It establishes that the historical split does not isolate unseen sequences. The experiment log also repeatedly compares the same test metric while selecting models, so that metric is part of development history.',
'The new evaluation fixes five group folds for sequences and five group folds for genes. Each fold checks that its grouping identifiers are disjoint between training and test and that identical sequences do not cross the partition. The gene-disjoint protocol asks a harder context-transfer question. The sequence-disjoint protocol permits familiar genes while holding out the sequences themselves.',
'One-hot Ridge is the simple baseline. A second Ridge model uses the existing engineered sequence features, with its scaler fitted only on training rows. The HRL extension discretizes assay-rank hypotheses into eight centers. Training responses anchor the training nodes; held-out nodes receive priors from the fitted sequence model. The sequence-similarity graph uses input features only, including held-out inputs in a declared transductive design.',
'No new hyperparameter selection is performed on these fold outcomes. The dataset and the original sequence features were already available during earlier project development, so these results remain exploratory rather than a pristine external confirmation. The distinction matters: changing the split improves the audit, but it does not erase prior access to the dataset.',
'I report pooled out-of-fold Spearman, mean fold Spearman and absolute prediction error. A small increase in one metric is a result to inspect. It is not a license to claim statistical significance or superiority across biological contexts.'],r'\rho_S=\operatorname{corr}(\operatorname{rank}(y),\operatorname{rank}(\widehat y)),\qquad\mathrm{MAE}=n^{-1}\sum_i|y_i-\widehat y_i|.',None),
('Prediction is a bridge to intervention',[
'A predictor orders observations under the conditions represented in its data. An intervention model asks what happens when I change a condition. The distinction is central to the cancer programme. A relation can be predictive because it tracks context, selection or measurement structure, even when manipulating it would not produce the predicted benefit.',
'The CRISPR table supplies measured assay ranks from defined experiments. Its benchmark asks a prediction question under grouped partitions. The current body model asks a dynamical question under invented coefficients. Joining their outputs without a fitted observation and intervention map would create an appearance of causality that neither component has established.',
'To connect them, I would need an identified perturbation, a relevant cell context, longitudinal or otherwise discriminating outcomes and a mechanism for linking those outcomes to transition rates. I would also need healthy-context observations. Cancer selectivity concerns the contrast between desired and undesired effects; a malignant-cell score alone cannot supply that contrast.',
'Perturbation diversity is useful because it tests competing accounts. If several models fit the untreated data, an intervention that makes their predictions diverge can be informative. The selected experiment should be evaluated by its capacity to discriminate hypotheses, not solely by an optimistic predicted response. Independent replication determines whether the discrimination travels beyond the original setting.',
'I see this as the place where the virtual body earns its name. The model must connect a local change to a system-level consequence through explicit, tested interfaces. The current dissertation supplies inspectable components and a measured benchmark. It leaves the unmeasured causal links visible instead of filling them with a declaration of success.'],None,None),
('The body prototype: equations and assumptions',[
'I implement three abstract sites linked by shared exposure and conservative tumor transport. At each site the state contains sensitive population S, resistant population R, immune activity E, resource O and healthy reserve H. A systemic exposure C is shared, with assumed site penetration multipliers of 1, 0.65 and 0.4. These are dimensionless quantities with invented coefficients.',
'The tumor populations grow with resource-dependent logistic terms. Sensitive mass can convert to resistant mass through a phenomenological conversion term. Exposure and immune activity remove tumor mass. Immune activity is recruited by tumor burden and decays; exposure can reduce it. Resource supply depends on healthy reserve, while tumor burden consumes resource. Healthy reserve repairs toward one and declines under exposure.',
'The systemic exposure obeys a one-compartment input-clearance equation. The model does not claim validated pharmacokinetics for a drug. The sites are not named organs, and the transport matrix is not a validated metastasis network. Individual cell mechanics, intracellular signaling, explicit vessels and patient-specific toxicity are absent from this prototype.',
'I compare four fictional controls: zero input, continuous input, a periodic pulse and a burden/reserve feedback rule. The thresholds and signal amplitudes are assumed engineering choices. They were not optimized for a patient and must not be read as dosing instructions. Their purpose is to expose selection and reserve tradeoffs inside the implemented equations.',
'The complete equations and parameters are in the source bundle. Each nominal trajectory is recorded as a CSV; each sampled parameter case retains its coefficients and outcome metrics. The later pages examine those records individually, so the mathematical assumptions remain connected to the numerical results they generate.'],r'\dot C=u-\kappa C,\qquad\dot H_i=a(1-H_i)-b p_i C H_i,\qquad c_i=p_iC.',None),
('Conservation, positivity and numerical work',[
'A virtual body must account for what moves and what changes identity. The prototype transport matrix has nonnegative off-diagonal entries and zero column sums. Consequently the intersite transport terms conserve each clone\'s total mass when isolated from the other processes. Sensitive-to-resistant conversion also cancels in the total tumor balance. These are direct algebraic checks on the implemented model.',
'At zero tumor population, the vector field does not create a negative population. At the resource and reserve boundaries, the continuous equations point inward under the stated positive coefficients. These properties describe the vector field. They do not guarantee that an explicit numerical step at an arbitrary size will stay inside the domain.',
'The simulator uses a fourth-order Runge-Kutta update with the control held constant within each step. It rejects nonfinite or negative states and excursions beyond the resource/reserve bounds. I repeat the nominal trajectories at half the time step. The largest final-state difference is about 0.000247 for the switching feedback rule; the other controls show smaller differences. This is a refinement diagnostic, not a proof for every possible future parameter set.',
'The exposure equation under constant input has an analytic solution. I use it to check the numerical implementation independently. Input integrals are computed from the held signal across each step, preserving the actual implemented control rather than approximating a discontinuous signal as a smooth curve.',
'These checks make the numbers more trustworthy as consequences of the equations. They do not make the coefficients biological measurements. That distinction lets me strengthen the computation without overstating its application. I want the model to survive both kinds of examination: arithmetic verification and experimental challenge.'],r'\mathbf 1^T L=0,\qquad C(t)=C(0)e^{-\kappa t}+\frac{u}{\kappa}(1-e^{-\kappa t}).',None),
('Tumor-free stability: the sharp question',[
'I ask whether constant exposure can make the tumor-free equilibrium locally asymptotically stable while retaining an assumed healthy-reserve floor. This is sharper than asking whether a plotted tumor curve becomes small. Near zero tumor burden, the model\'s immune recruitment vanishes, resource approaches one and reserve approaches a positive exposure-dependent equilibrium.',
'The clone invasion Jacobian is block triangular. The sensitive block contains resource-free growth adjusted by conversion, exposure killing and migration. The resistant block contains resistant growth, exposure killing and migration. The conversion term occupies a lower off-diagonal block. It does not alter the eigenvalues of the triangular system.',
'For the symmetric transport matrix used here, raising exposure subtracts a strictly positive diagonal matrix from each clone block. The largest eigenvalue therefore decreases strictly. A bracketed root calculation finds the unique positive-to-negative crossing. Strictly negative largest eigenvalues in both blocks certify local exponential stability. A zero eigenvalue is nonhyperbolic and does not, by itself, settle nonlinear stability. Every exposure permitted by the nominal reserve constraint retains a positive resistant eigenvalue, which establishes instability there.',
'The nominal resistant crossing occurs at 5.181195 dimensionless exposure. Preserving a reserve floor of 0.7 permits at most 0.136364. Those intervals do not intersect. The same comparison is infeasible in every one of the twenty-four arbitrary parameter configurations. This is a substantive limitation exposed by the calculation, not a judgment about all cancer biology.',
'The theorem concerns local stability and constant exposure in the specified equations. It does not decide arbitrary time-varying controls, other mechanisms or clinical cures. I preserve that scope because it is exactly what makes the result reproducible and falsifiable. The case pages give each threshold, reserve limit and sampled parameter set.'],r'A_R(C)=\operatorname{diag}(r_R-k_Rp_iC)+mL,\quad C\leq\frac{a(1-h_0)}{b\,p_{\max}h_0}.',None),
('The nested implementation and its repairs',[
'The existing HRL2026 code contains the cell-of-cells recursion that motivated the present architecture. Its original full step fails because it calls a membrane method that is not defined. I preserve the original files and create an isolated audited snapshot, so that the research record distinguishes the inherited implementation from the repair.',
'The missing entropy observation is computed from the current categorical state. I do not invent an undocumented physical membrane equation to make the method name work. The entropy helper normalizes nonnegative weights before applying Shannon\'s definition and rejects invalid inputs. A uniform normalized three-state distribution therefore has normalized entropy one, and a point mass has entropy zero.',
'A state-change metric also needs an old state that remains old after mutation. The original local variable aliases the array row being overwritten. Copying that row before the assignment restores the intended change measurement. The final repair separates uncertain projection from a certain negative category by giving abstention its own code.',
'The diagnostic builds a seven-node hierarchy with three levels and runs ten recursive steps. Every node advances, every state row remains finite and nonnegative with unit mass, entropy remains within its normalized range, and the initial reported change is nonzero. These checks establish execution properties of a categorical relaxation hierarchy.',
'I have not established physical cell physiology by running that hierarchy. The recursion does not yet implement measured intercellular traffic or calibrated intracellular dynamics. What I have established is a repaired, inspectable substrate on which such mappings can be tested. The distinction prevents an implementation defect from being hidden behind the word virtual.'],None,None),
('From computation to a biological claim',[
'I want this programme to reach a result that matters outside the simulator. That requires a chain of evidence: defined context, identified observation model, reproducible prediction, discriminating perturbation, independent experimental replication and appropriate clinical investigation. Each link answers a question the previous link cannot answer by itself.',
'The Human Tumor Atlas and DepMap are candidate resources for measured spatial context and cancer dependencies [6,7]. They were not downloaded or fitted for the executed dissertation. PhysiCell is an established multicellular framework that can provide a future mechanistic comparison [5]; it is not integrated into the present prototype. The virtual-cell perspective by Bunne and colleagues frames a research agenda rather than documenting a complete virtual human [4].',
'A next empirical claim should be specific enough to fail: for example, an accurately defined perturbation-response endpoint in a specified cancer context on a held-out laboratory or donor set. A retrospective improvement of a few thousandths in correlation is not the same endpoint. A local stability proof for invented rates is not the same endpoint either.',
'Patient benefit also requires safety evidence. A putative intervention can have off-target effects, delivery limitations, context dependence and organism-level toxicity that are invisible to an assay-rank predictor. The body hierarchy is valuable because it gives these constraints a place in the model. Their presence as variables still requires measured calibration.',
'My ambition remains to cure cancer. The responsibility of the dissertation is to show what I have computed and what conclusion that computation licenses. The evidence here supports a research programme with executed components, real assay prediction and exposed model limits. It does not support a declaration that a cancer cure has been established.'],None,None),
('Reproducibility and primary sources',[
'I supply the manuscript, generated LaTeX, measured out-of-fold prediction records, synthetic trajectories, parameter cases, verification records, color figures and generation script. The associated computational source bundle contains the simulator, sparse HRL engine, portable sequence-feature extraction and repaired nested-cell snapshot. File hashes connect the products to their inputs.',
'The measured source table is identified by its SHA-256 and its MicrosoftResearch/Azimuth URL in the audit record. The historical highest-scoring predictor is not reproduced by the new Ridge/HRL comparison. The fixed grouped benchmarks are a separate exploratory evaluation, with all fold outcomes retained. That distinction is necessary for a fair comparison.',
'I rely on the following primary sources for context and definitions. Their findings are not silently substituted for measurements in my prototype. Reference numbers identify contextual support; the actual new results appear in the supplied run records.'],None,None)
]
for title,body,eq,fig in core:p(title,body,figure=fig,caption='Conceptual cross-scale architecture; intended interfaces require biological calibration.' if fig else '',equation=eq)
assert len(pages)==19
# References reside on page 19, adjacent to the reproducibility protocol.
pages[-1]['references']=[
'[1] Rosenfeld, Hummel and Zucker (1976). Scene labeling by relaxation operations. IEEE Transactions on Systems, Man, and Cybernetics 6:420-433. DOI: 10.1109/TSMC.1976.4309519.',
'[2] Hummel and Zucker (1983). On the foundations of relaxation labeling processes. IEEE TPAMI 5:267-287. DOI: 10.1109/TPAMI.1983.4767390.',
'[3] Doench et al. (2016). Optimized sgRNA design to maximize activity and minimize off-target effects of CRISPR-Cas9. Nature Biotechnology 34:184-191. DOI: 10.1038/nbt.3437.',
'[4] Bunne et al. (2024). How to build the virtual cell with artificial intelligence: Priorities and opportunities. Cell 187:7045-7063. DOI: 10.1016/j.cell.2024.11.015. Local preprint: arXiv:2409.11654v2.',
'[5] Ghaffarizadeh et al. (2018). PhysiCell: An open source physics-based cell simulator for 3-D multicellular systems. PLOS Computational Biology 14:e1005991. DOI: 10.1371/journal.pcbi.1005991.',
'[6] National Cancer Institute. Cancer Systems Biology Consortium. cancer.gov/about-nci/organization/dcb/research-programs/csbc. Human Tumor Atlas access: docs.humantumoratlas.org/data_access/introduction/.',
'[7] Broad Institute. DepMap Portal, dataset access and release information: depmap.org/portal/data_page/. Resource pages checked 4 October 2026.']
# Ten detailed held-out fold reports.
for protocol,groups in [('sequence_disjoint',df['30mer'].to_numpy()),('gene_disjoint',df['Target gene'].to_numpy())]:
 for fold,(train,test) in enumerate(GroupKFold(n_splits=5).split(df,df.score_drug_gene_rank,groups)):
  record=next(x for x in r['folds'] if x['protocol']==protocol and x['fold']==fold);a=OOF[protocol].iloc[test];name=f'fold-{protocol}-{fold}'
  fig,axs=plt.subplots(1,3,figsize=(8.2,2.15),layout='constrained')
  for ax,m,col,label in zip(axs,models,colors,names):
   ax.hexbin(a.observed_rank,a[m],gridsize=24,mincnt=1,cmap='viridis');ax.plot([0,1],[0,1],color='#d55e00',lw=.8);ax.set(xlabel='Observed assay rank',ylabel='OOF prediction',title=label)
  save(fig,name)
  best=max(record['spearman'],key=record['spearman'].get);delta=record['spearman']['hrl_sequence_graph']-record['spearman']['existing_sequence_features_ridge']
  body=[f'I report {protocol.replace("_"," ")} fold {fold+1} as a complete held-out result, rather than allowing its contribution to disappear into the pooled score. The training set contains {len(train):,} rows; the test set contains {len(test):,}. Group identifiers and identical sequences are disjoint across this partition. Test responses are used only for the final calculation of error and rank correlation.',
  f'The largest Spearman point estimate in this fold belongs to {names[models.index(best)]}. The HRL change relative to engineered Ridge is {delta:+.6f}. Its sign describes this partition; it does not establish a general effect. The fold contains {df.iloc[test]["Target gene"].nunique()} gene contexts, with a mean observed rank of {a.observed_rank.mean():.4f} and a standard deviation of {a.observed_rank.std():.4f}.',
  f'The HRL update converged in {record["hrl_iterations"]} iterations. I keep this convergence result separate from predictive quality. The sequence graph is feature-only and transductive, so held-out input sequences participate in its construction while their assay responses remain unavailable to inference. Scaling of the engineered features is fitted on training rows.',
  'The density panels show how prediction varies across the supplied response range. The orange line is equality of predicted and observed rank, not a physiological reference. Compression, tails and scatter are visible even when a correlation is positive. This page supplies one denominator in the larger audit; it does not convert a guide-response predictor into a cancer-treatment model.']
  table=[['Model','Spearman','Test MAE']]+[[names[i],f'{record["spearman"][m]:.6f}',f'{np.mean(np.abs(a.observed_rank-a[m])):.6f}'] for i,m in enumerate(models)]
  p(f'Held-out report: {protocol.replace("_"," ")}, fold {fold+1}',body,name,'Measured assay ranks and held-out predictions. Color shows point density; every panel uses this fold\'s held-out rows.',table,kind='Measured fold result')
assert len(pages)==29
# Six model/protocol diagnostics including a measured 3D view.
for protocol in OOF:
 a=OOF[protocol]
 for m,label,col in zip(models,names,colors):
  n=f'model-{protocol}-{m}';error=a[m]-a.observed_rank;metric=next(x for x in r['metrics'] if x['protocol']==protocol and x['model']==m)
  fig,axs=plt.subplots(1,3,figsize=(8.2,2.25),layout='constrained')
  axs[0].hist(error,bins=35,color=col,alpha=.8);axs[0].axvline(0,color='black',lw=.7);axs[0].set(xlabel='Prediction minus observed rank',ylabel='Rows',title='Signed error')
  bins=pd.qcut(a[m],10,duplicates='drop');g=a.groupby(bins,observed=True).agg(pred=(m,'mean'),obs=('observed_rank','mean'));axs[1].plot(g.pred,g.obs,'o-',color=col);axs[1].plot([0,1],[0,1],color='black',lw=.7);axs[1].set(xlabel='Mean prediction in bin',ylabel='Mean observed rank',title='Descriptive response curve')
  ff=[x['spearman'][m] for x in r['folds'] if x['protocol']==protocol];axs[2].bar(range(1,6),ff,color=col);axs[2].set(xlabel='Fold',ylabel='Spearman',title='Fold variability',ylim=(0,.6));save(fig,n)
  body=[f'I examine {label} under the {protocol.replace("_"," ")} protocol across all {len(a):,} out-of-fold predictions. Every source row receives a prediction from a fit that excludes its group. The pooled rank correlation is {metric["pooled_oof_spearman"]:.6f}; the mean of the five fold correlations is {metric["mean_fold_spearman"]:.6f}. These are different summaries with different weighting.',
  f'The signed-error mean is {error.mean():+.6f}, the root-mean-square error is {np.sqrt(np.mean(error**2)):.6f}, and the mean absolute error is {metric["MAE"]:.6f}. Prediction extrema are {a[m].min():.4f} and {a[m].max():.4f}. Ridge predictions are not constrained to the response interval; the HRL expectation is a weighted mean over eight centers within it. That interface difference is part of the comparison.',
  'The response-curve panel groups predictions into quantile bins and compares mean prediction with mean observed rank. It is a descriptive check on the supplied response scale. It is not a probability-calibration curve, because these outputs are assay-rank estimates rather than event probabilities. The error histogram exposes signed deviations that rank correlation alone cannot summarize.',
  f'The fold correlations range from {min(ff):.6f} to {max(ff):.6f}. I retain this variation rather than reporting only the pooled score. These partitions are not five independent laboratory replications: they share the underlying dataset and training information across fits. No significance test or confidence interval is claimed from the displayed variation.']
  table=[['Diagnostic','Value'],['Pooled Spearman',f'{metric["pooled_oof_spearman"]:.6f}'],['Mean fold Spearman',f'{metric["mean_fold_spearman"]:.6f}'],['MAE',f'{metric["MAE"]:.6f}'],['RMSE',f'{np.sqrt(np.mean(error**2)):.6f}']]
  p(f'Model diagnostic: {label} / {protocol.replace("_"," ")}',body,n,'Measured out-of-fold errors, descriptive response curve and fold scores. These are prediction diagnostics, not efficacy endpoints.',table,kind='Measured model diagnostic')
assert len(pages)==35
# Seventeen gene-context pages; all contexts preserved, no therapeutic ranking.
for gene,idx in df.groupby('Target gene',sort=True).groups.items():
 d=df.loc[idx];a=OOF['gene_disjoint'].loc[idx];n=f'gene-{gene}';drugs=d.drug.value_counts();rho={m:float(spearmanr(a.observed_rank,a[m]).statistic) for m in models}
 fig,axs=plt.subplots(1,2,figsize=(8.2,2.15),layout='constrained')
 axs[0].hist(d.score_drug_gene_rank,bins=20,color=colors[0]);axs[0].set(xlabel='Observed assay rank',ylabel='Rows',title=f'{gene}: supplied response distribution')
 axs[1].hexbin(a.observed_rank,a.hrl_sequence_graph,gridsize=20,mincnt=1,cmap='viridis');axs[1].plot([0,1],[0,1],color='#d55e00',lw=.8);axs[1].set(xlabel='Observed assay rank',ylabel='Gene-disjoint HRL prediction',title='Held-out context');save(fig,n)
 body=[f'I keep the {gene} context visible because pooled prediction quality can hide a gene-specific failure. This context contains {len(d):,} measured rows and {d["30mer"].nunique():,} distinct sequences in {len(drugs)} supplied drug-context categories. Its response mean is {d.score_drug_gene_rank.mean():.4f}; its median is {d.score_drug_gene_rank.median():.4f}. Those ranks describe the assay table, not cancer outcomes.',
 f'All predictions on this page come from the gene-disjoint out-of-fold record. The model did not fit response labels from this target-gene group in its corresponding fold. The HRL within-context Spearman estimate is {rho["hrl_sequence_graph"]:.6f}, compared with {rho["existing_sequence_features_ridge"]:.6f} for engineered Ridge. The within-context MAE for HRL is {np.mean(np.abs(a.hrl_sequence_graph-a.observed_rank)):.6f}.',
 'The grouping controls identical-sequence overlap across training and test, but it does not create an independent laboratory dataset. Context-normalized targets are supplied by the source. Repeated assay conditions and rank construction can affect their distribution. I therefore use the page to inspect model transfer, rather than to infer that a particular gene should be altered therapeutically.',
 f'The observed response range is {d.score_drug_gene_rank.min():.4f} to {d.score_drug_gene_rank.max():.4f}. The distribution and held-out density plot expose where the estimator compresses that range or fails to preserve order. A gene label supplies a context for this error audit; it does not establish cancer dependence, healthy-tissue selectivity, safe delivery or patient benefit.']
 table=[['Model','Within-context Spearman','MAE']]+[[names[i],f'{rho[m]:.6f}',f'{np.mean(np.abs(a[m]-a.observed_rank)):.6f}'] for i,m in enumerate(models)]
 p(f'Gene-context audit: {gene}',body,n,'Measured response distribution and gene-disjoint held-out prediction density. Gene identity is a context annotation, not a treatment recommendation.',table,kind='Measured gene context')
assert len(pages)==52
# Four dynamical reports with complete nominal results.
for policy in ['none','continuous','pulsed','feedback']:
 rows=pd.read_csv(B/f'data/{policy}.csv');q=sim['nominal'][policy];n=f'policy-{policy}'
 fig,axs=plt.subplots(1,3,figsize=(8.2,2.15),layout='constrained')
 for i,site in enumerate(['primary','secondary','third']):
  axs[0].plot(rows.time,rows[f'{site}_sensitive']+rows[f'{site}_resistant'],color=colors[i],label=site)
  axs[1].plot(rows.time,rows[f'{site}_reserve'],color=colors[i]);axs[2].plot(rows.time,rows[f'{site}_resource'],color=colors[i])
 for ax,title in zip(axs,['Tumor population by site','Healthy reserve','Resource']):ax.set(xlabel='Dimensionless time',title=title);ax.grid(alpha=.2)
 axs[0].legend(fontsize=6);save(fig,n)
 body=[f'I report the {policy} control as a consequence of the nominal synthetic equations. The run ends at dimensionless time 50 with total tumor burden {q["final_burden"]:.6f}, integrated tumor burden {q["burden_integral"]:.6f}, and minimum healthy reserve {q["min_reserve"]:.6f}. None of these quantities is a measured patient endpoint.',
 f'The final resistant fraction is {q["final_resistant_fraction"]:.6f}. The integrated fictional input is {q["input_integral"]:.6f}. A changing fraction must be interpreted with the corresponding total population: a large resistant fraction can coexist with a smaller total burden, and a small fraction can coexist with substantial absolute mass. Selection and suppression are different aspects of the same trajectory.',
 'The three panels retain site-specific behavior. Their differences arise from assumed penetration, initial population and transport, not from calibrated organ physiology. Healthy reserve influences resource supply, and resource influences growth. The shared exposure can therefore change the system through both direct tumor removal and indirect alteration of its environment.',
 'The numerical refinement checks pass for the nominal controls. They increase confidence that the implementation follows its stated equations at the chosen time step. They do not turn an invented coefficient into a measured effect. I use this trajectory to identify questions about resistance and reserve that a biologically calibrated model would need to answer.']
 table=[['Synthetic outcome','Value']]+[[k.replace('_',' '),f'{v:.6f}'] for k,v in q.items()]
 p(f'Nominal body trajectory: {policy}',body,n,'Synthetic, dimensionless site trajectories. Penetration and kinetics are assumptions; the controls are fictional signals rather than doses.',table,kind='Synthetic dynamical result')
assert len(pages)==56
# Twenty-four independent parameter ledgers, with paired policy comparisons.
for e in ext['ensemble']:
 i=e['replicate'];cases=[x for x in sim['ensemble'] if x['replicate']==i];params=cases[0]['parameters'];n=f'case-{i:02d}'
 fig,axs=plt.subplots(1,2,figsize=(8.2,2.15),layout='constrained')
 for j,c in enumerate(cases):axs[0].scatter(c['min_reserve'],c['final_burden'],color=colors[j],s=45,label=c['policy'])
 axs[0].set(xlabel='Minimum reserve over finite run',ylabel='Final tumor burden',title='Paired finite-horizon controls');axs[0].legend(fontsize=6)
 threshold=e['required_exposure_strictly_greater_than'];limit=e['maximum_exposure_for_reserve_floor'];C=np.linspace(0,threshold*1.2,180)
 for j,pen in enumerate([1.,.65,.4]):axs[1].plot(C,params['repair']/(params['repair']+params['toxicity']*pen*C),color=colors[j],label=f'Site {j+1}')
 axs[1].axhline(.7,color='black',ls='--',lw=.8);axs[1].axvline(threshold,color=colors[3],ls=':',lw=1);axs[1].axvspan(0,limit,color=colors[2],alpha=.15);axs[1].set(xlabel='Constant dimensionless exposure',ylabel='Equilibrium reserve',title='Stability threshold and reserve');save(fig,n)
 best=min(cases,key=lambda x:x['final_burden']);reservebest=max(cases,key=lambda x:x['min_reserve']);ratio=threshold/limit
 body=[f'I examine parameter configuration {i+1:02d} with the same sampled coefficients used for each of its four control runs. This pairing keeps a control comparison from being confused with a change of biological assumptions. The sampled sensitive growth coefficient is {params["growth"]:.5f}; resistant growth is {params["resistant_growth"]:.5f}; resistant exposure killing is {params["kill_resistant"]:.5f}; the toxicity coefficient is {params["toxicity"]:.5f}. These values were drawn from arbitrary engineering ranges.',
 f'The smallest final burden among the four tested controls occurs under {best["policy"]}, at {best["final_burden"]:.6f}. The largest minimum reserve occurs under {reservebest["policy"]}, at {reservebest["min_reserve"]:.6f}. This finite list does not solve an optimal-control problem. It records the actual tradeoff reached by the fixed fictional controls under this one parameter set.',
 f'The constant-exposure stability threshold is {threshold:.6f}. The reserve-floor limit is {limit:.6f}, so the required threshold is {ratio:.2f} times that allowed limit. At the threshold, minimum equilibrium reserve is {e["minimum_equilibrium_reserve_at_threshold"]:.6f}. Resistant invasion at the reserve limit remains positive, at {e["resistant_invasion_at_reserve_limit"]:.6f}. The feasible constant-exposure intersection is empty.',
 'The finite-horizon panel and the equilibrium panel answer different questions. A favorable endpoint at time 50 does not establish stability at vanishing tumor burden; an equilibrium constraint does not describe every time-varying strategy. I keep both visible. This case is a sensitivity calculation in an uncalibrated model, not a patient forecast or a sampled member of a biological population.']
 if i==23:body.append('I close this record with the purpose intact: to cure cancer by making the virtual body answerable to the living body. Let it be written. Let it be calculated. Let it be tested. The completed calculations remain available for correction, extension and experimental challenge.')
 table=[['Control','Final burden','Min. reserve','Resistant fraction']]+[[c['policy'],f'{c["final_burden"]:.5f}',f'{c["min_reserve"]:.5f}',f'{c["final_resistant_fraction"]:.5f}'] for c in cases]
 p(f'Parameter ledger {i+1:02d}: resistance and reserve',body,n,'Synthetic paired-control outcomes and analytic equilibrium reserve. Green shading: assumed reserve-permitted exposure. Dotted line: clone-stability threshold.',table,kind='Synthetic sensitivity case')
assert len(pages)==80
# Extra overview figures: actual measured diagnostic in 3D and analytic surface.
fig=plt.figure(figsize=(8.2,4.0));ax=fig.add_subplot(111,projection='3d');a=OOF['gene_disjoint'];valid=df['Percent Peptide'].notna();idx=np.flatnonzero(valid)[::3];points=ax.scatter(df.loc[idx,'Percent Peptide'],a.loc[idx,'observed_rank'],a.loc[idx,'hrl_sequence_graph'],c=np.abs(a.loc[idx,'hrl_sequence_graph']-a.loc[idx,'observed_rank']),cmap='viridis',s=5,alpha=.7);ax.set(xlabel='Percent Peptide annotation',ylabel='Observed assay rank',zlabel='Gene-disjoint HRL estimate',title='Measured assay diagnostic: annotation, response and held-out estimate');fig.colorbar(points,ax=ax,shrink=.65,label='Absolute prediction error');save(fig,'measured-3d')
fig=plt.figure(figsize=(8.2,4));ax=fig.add_subplot(111,projection='3d');c,tox=np.meshgrid(np.linspace(0,6,70),np.linspace(.04,.2,70));h=.035/(.035+tox*c);surf=ax.plot_surface(c,tox,h,cmap='viridis',linewidth=0,antialiased=True);ax.set(xlabel='Constant dimensionless exposure',ylabel='Assumed toxicity coefficient',zlabel='Equilibrium reserve',title='Analytic surface of the synthetic reserve equation');save(fig,'reserve-3d')
# Place these rich views on core pages rather than changing the page count.
pages[10]['figure']='measured-3d';pages[10]['caption']='Measured diagnostic with every third eligible assay row shown. Percent Peptide is an annotation, not the response. The annotation is excluded from benchmark predictors. The view is descriptive, not a causal surface.'
pages[15]['figure']='reserve-3d';pages[15]['caption']='Analytic surface from the synthetic reserve equation at penetration one and repair 0.035. It is not fitted to patient injury data.'
# Typography and explicit page boundaries make each report independently inspectable.
def esc(s):
 s=s.replace('’',"'").replace('–','-').replace('—','-')
 chunks=re.split(r'(\$[^$]+\$)',s)
 for i in range(0,len(chunks),2):
  for old,new in [('\\',r'\textbackslash{}'),('&',r'\&'),('%',r'\%'),('_',r'\_'),('#',r'\#'),('{',r'\{'),('}',r'\}')]:chunks[i]=chunks[i].replace(old,new)
 return ''.join(chunks)
header=r'''\documentclass[10pt]{article}
\usepackage[a4paper,top=.67in,bottom=.67in,left=.72in,right=.72in,headheight=14pt]{geometry}
\usepackage[T1]{fontenc}\usepackage[utf8]{inputenc}\usepackage{lmodern,microtype,amsmath,amssymb,graphicx,xcolor,booktabs,tabularx,hyperref,fancyhdr}
\definecolor{ink}{HTML}{153F50}\definecolor{accent}{HTML}{0072B2}\definecolor{green}{HTML}{009E73}
\hypersetup{colorlinks=true,urlcolor=accent,pdftitle={To Cure Cancer: The Virtual Body},pdfauthor={Michael Emanuel Glover}}
\setlength{\parindent}{0pt}\setlength{\parskip}{6pt}\setlength{\emergencystretch}{3em}
\pagestyle{fancy}\fancyhf{}\fancyhead[L]{\small\color{ink}THE VIRTUAL BODY | COMPUTATIONAL DISSERTATION}\fancyhead[R]{\small Glover | 2026}\fancyfoot[L]{\scriptsize Evidence, equations, implementation}\fancyfoot[R]{\thepage}
\begin{document}
'''
tex=[header];md=['# To Cure Cancer: The Virtual Body\n\nMichael Emanuel Glover. Developed with Codex. 4 October 2026.\n']
for i,page in enumerate(pages):
 if i:tex.append(r'\clearpage')
 tex.append(r'\hypertarget{p'+str(i+1)+r'}{}')
 tex.append(r'{\small\color{accent}\MakeUppercase{'+esc(page['kind'])+r'}}\par')
 tex.append(r'{\LARGE\bfseries\color{ink}'+esc(page['title'])+r'}\par\vspace{5pt}')
 if i==0:tex.append(r'{\large Michael Emanuel Glover}\par Developed in dialogue with Codex | 4 October 2026\par\vspace{7pt}')
 md.append(f'\n## Page {i+1}: {page["title"]}\n')
 for para in page['body']:tex.append(esc(para)+r'\par');md.append(para+'\n')
 if page.get('equation'):tex.append(r'\['+page['equation']+r'\]');md.append('\n\\[\n'+page['equation']+'\n\\]\n')
 if page.get('table'):
  rows=page['table'];cols=len(rows[0]);tex.append(r'\vspace{3pt}{\small\begin{tabularx}{\linewidth}{'+('X'+'r'*(cols-1))+r'}\toprule')
  for j,row in enumerate(rows):tex.append(' & '.join(esc(str(v)) for v in row)+r'\\'+(r'\midrule' if j==0 else ''))
  tex.append(r'\bottomrule\end{tabularx}}\par');md.append('\n'+'\n'.join('| '+' | '.join(map(str,row))+' |' for row in rows)+'\n')
 if page.get('figure'):
  height='.235' if i<19 else '.205'
  tex.append(r'\begin{center}\includegraphics[width=.97\linewidth,height='+height+r'\textheight,keepaspectratio]{figures/'+page['figure']+r'.pdf}\end{center}')
  tex.append(r'{\footnotesize\color{ink}'+esc(page['caption'])+r'\par}')
  md.append(f'\nFigure: figures/{page["figure"]}.pdf\n{page["caption"]}\n')
 if page.get('references'):
  for ref in page['references']:tex.append(r'{\footnotesize '+esc(ref)+r'\par}');md.append(ref+'\n')
tex.append(r'\end{document}')
(B/'VIRTUAL-BODY-DISSERTATION.tex').write_text('\n'.join(tex));(B/'MANUSCRIPT.md').write_text('\n'.join(md));(B/'VIRTUAL-BODY-DISSERTATION.txt').write_text('\n'.join(md));(B/'page-ledger.json').write_text(json.dumps({'pages':pages,'figure_count':figcount,'words':len(re.findall(r"\b[\w'-]+\b",' '.join(md)))},indent=2))
for _ in range(2):
 z=subprocess.run(['pdflatex','-interaction=nonstopmode','-halt-on-error','VIRTUAL-BODY-DISSERTATION.tex'],cwd=B,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
 if z.returncode:print(z.stdout[-4000:]);raise SystemExit(z.returncode)
info=subprocess.check_output(['pdfinfo',str(B/'VIRTUAL-BODY-DISSERTATION.pdf')],text=True);print(info);print('Figures:',figcount,'words:',len(re.findall(r"\b[\w'-]+\b",' '.join(md))))
