from pathlib import Path
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image, Preformatted

ROOT=Path(__file__).parent; ROOT.mkdir(exist_ok=True)

def charts():
    plt.style.use('seaborn-v0_8-whitegrid')
    x=['Resource\ncontrol','Learning','Network\neffects','Switching\ncosts']
    y=[.78,.62,.88,.71]
    fig,ax=plt.subplots(figsize=(8.2,4.6)); ax.bar(x,y,color=['#39c6d7','#7de2a8','#f5c451','#ef7b9a']); ax.set_ylim(0,1); ax.set_ylabel('Illustrative mechanism strength (0–1)'); ax.set_title('First-mover mechanisms: conceptual comparison'); ax.text(.01,-.18,'Illustrative scores, not estimated observations.',transform=ax.transAxes,fontsize=8); fig.tight_layout(); fig.savefig(ROOT/'mechanisms.png',dpi=180); plt.close(fig)
    t=list(range(1,13)); incumbent=[.25+.045*i for i in t]; entrant=[.62-.018*i for i in t]
    fig,ax=plt.subplots(figsize=(8.2,4.6)); ax.plot(t,incumbent,'o-',label='incumbent option value',color='#39c6d7'); ax.plot(t,entrant,'o-',label='entrant outside option',color='#ef7b9a'); ax.axvline(6,ls='--',color='#f5c451',label='policy/entry window'); ax.set_xlabel('period'); ax.set_ylabel('normalized value'); ax.set_title('Toy entry-arbitrage window'); ax.legend(); fig.tight_layout(); fig.savefig(ROOT/'entry_window.png',dpi=180); plt.close(fig)
    cats=['open access','interoperability','disclosure','antitrust']; vals=[.31,.42,.56,.49]
    fig,ax=plt.subplots(figsize=(8.2,4.6)); ax.barh(cats,vals,color='#7de2a8'); ax.set_xlim(0,1); ax.set_xlabel('Illustrative reduction in lock-in (0–1)'); ax.set_title('Policy levers as counterweights to early control'); fig.tight_layout(); fig.savefig(ROOT/'policy_levers.png',dpi=180); plt.close(fig)

def P(t,s): return Paragraph(t,s)
def build():
    charts(); ss=getSampleStyleSheet();
    ss.add(ParagraphStyle(name='TX',parent=ss['Title'],fontName='Helvetica-Bold',fontSize=27,leading=32,textColor=colors.HexColor('#10384a'),alignment=TA_CENTER,spaceAfter=16))
    ss.add(ParagraphStyle(name='Sub',parent=ss['Normal'],fontSize=13,leading=18,textColor=colors.HexColor('#376577'),alignment=TA_CENTER,spaceAfter=20))
    ss.add(ParagraphStyle(name='H',parent=ss['Heading1'],fontSize=20,leading=24,textColor=colors.HexColor('#0e7182'),spaceAfter=12))
    ss.add(ParagraphStyle(name='B',parent=ss['BodyText'],fontSize=12,leading=18,spaceAfter=11))
    ss.add(ParagraphStyle(name='S',parent=ss['BodyText'],fontSize=8.5,leading=11,textColor=colors.HexColor('#49616a')))
    ss.add(ParagraphStyle(name='C',fontName='Courier',fontSize=8,leading=10,backColor=colors.HexColor('#eef7f5'),borderPadding=8))
    out=ROOT/'political_economy_keyholes_and_first_moves.pdf'; doc=BaseDocTemplate(str(out),pagesize=letter,rightMargin=.65*inch,leftMargin=.65*inch,topMargin=.62*inch,bottomMargin=.6*inch)
    frame=Frame(doc.leftMargin,doc.bottomMargin,doc.width,doc.height,id='f')
    def foot(c,d):
        c.saveState(); c.setStrokeColor(colors.HexColor('#d4e8e5')); c.line(doc.leftMargin,.43*inch,letter[0]-doc.rightMargin,.43*inch); c.setFont('Helvetica',8); c.setFillColor(colors.HexColor('#55727a')); c.drawString(doc.leftMargin,.27*inch,'Political Economy Working Paper · keyholes, camouflage, and first moves'); c.drawRightString(letter[0]-doc.rightMargin,.27*inch,str(d.page)); c.restoreState()
    doc.addPageTemplates([PageTemplate(id='all',frames=frame,onPage=foot)]); story=[]
    notes={
      'Abstract':'The paper treats first-mover advantage as an institutional and informational phenomenon, not a guarantee of permanent dominance.',
      '1. Problem and contribution':'The central question is who gets to shape the field on which later choices are made.',
      '2. A vocabulary of keyholes':'A keyhole is a constraint on visibility, access, and interpretation—not merely a lack of information.',
      '3. Ownership as an option set':'Ownership changes the set of future moves available to an actor and to everyone else.',
      '4. First-mover advantage':'Early entry is valuable only when control, learning, or coordination survives imitation.',
      '5. Camouflage and information':'Opacity can preserve an option, but lawful strategy is different from deception or fraud.',
      '6. Arbitrage and non-drawing states':'Arbitrage converts a valuation mismatch into a durable allocation or bargaining advantage.',
      '7. Network effects and standards':'Standards can turn an early move into infrastructure; interoperability can reopen the field.',
      '8. Property, law, and legitimacy':'Property rights are political institutions whose boundaries determine the option space.',
      '9. A Bayesian game of entry':'Different players can rationally assign different probabilities to the same future.',
      '10. Model and propositions':'The model is a map for comparison, not a machine that predicts every market.',
      '11. Cases and mechanisms':'Cases should be compared by mechanism—control, learning, network, or switching—not by slogan.',
      '12. Policy counterweights':'The public problem is not early action itself; it is unreviewable exclusion.',
      '13. Measurement and evidence':'Claims about advantage require a counterfactual: what would have happened without early control?',
      '14. Implications for democratic political economy':'A fair field preserves entry, voice, exit, and revision.',
      'Conclusion':'The keyhole can be widened without pretending that all positions begin equal.',
    }
    def page(title,paras,extra=None):
        story.append(P(title,ss['H'])); story.extend([P(x,ss['B']) if isinstance(x,str) else x for x in paras])
        if extra: story.extend(extra)
        box=Table([[P('WORKING NOTE',ss['S']),P(notes[title],ss['B'])]],colWidths=[1.35*inch,5.35*inch],style=TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#e4f5f0')),('BOX',(0,0),(-1,-1),.8,colors.HexColor('#39aab3')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),10),('RIGHTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),5)])); story.extend([Spacer(1,.14*inch),box,PageBreak()])
    story += [Spacer(1,1.2*inch),P('Keyholes, Camouflage, and First Moves',ss['TX']),P('A political-economy paper on asset ownership, information asymmetry, arbitrage, and the institutional shaping of opportunity',ss['Sub']),Spacer(1,.25*inch),P('Working paper · 28 September 2026',ss['Sub']),P('<b>Scope.</b> This is a conceptual paper. Chess and hyperstar language are metaphors for strategic interaction. The empirical claims are limited to cited economic and policy literature.',ss['B']),PageBreak()]
    page('Abstract',['First-mover advantage is often described as if it were a property of speed. This paper argues that it is better understood as a change in the option set: an early actor may acquire a scarce asset, learn before rivals, establish a standard, or impose switching costs. The same move can create public value or durable exclusion depending on institutions.', 'The key-and-keyhole metaphor clarifies the information problem. A key is an action or asset; a keyhole is the constrained interface through which others can observe, enter, contest, or reinterpret it. Camouflage is strategic uncertainty around the key. Arbitrage is the conversion of a valuation gap into control or bargaining power.', 'The paper combines political economy, industrial organization, Bayesian games, property-rights theory, and a small set of policy propositions. It concludes that legitimate first action should be paired with contestability, disclosure, interoperability, and an accessible exit.'])
    page('1. Problem and contribution',['Markets do not begin from a blank board. Land, data, patents, infrastructure, platforms, licenses, and standards are already allocated when later participants arrive. First ownership can therefore shape the future choice architecture.', 'The contribution is a common language for three processes: objectification (reducing an opponent to a model), camouflage (hiding or delaying recognition of an option), and arbitrage (acting on a difference in valuations or constraints).'])
    page('2. A vocabulary of keyholes',['A keyhole is a constrained observation-and-action channel. In a market it may be a title registry, API, platform rule, patent boundary, procurement process, or credit score. It determines which actions are visible, affordable, and legitimate.', 'The metaphor is useful only if it remains institutional. A keyhole is built by law, technology, norms, and ownership; it is not simply a psychological limitation.'])
    page('3. Ownership as an option set',['Ownership is a bundle of enforceable rights, but bundles differ. Control, income, exclusion, transfer, and stewardship may be separated across actors. A first owner has an option to choose among future uses before rivals can bargain over them.', 'Let A be an asset and X(A) its feasible future uses. Ownership changes X for the owner and may shrink X for others. Political economy asks who authorizes that transformation and who bears the cost.'])
    page('4. First-mover advantage',["The classic mechanisms are technology leadership, resource control, learning, network effects, and buyer switching costs. None is automatic. A first mover can also bear pioneering costs, choose the wrong standard, reveal demand to followers, or become locked into legacy technology."], [Image(str(ROOT/'mechanisms.png'),width=6.8*inch,height=3.8*inch)])
    page('5. Camouflage and information',['Camouflage is not necessarily deception. It can be the ordinary opacity created by uncertainty, staged investment, private experimentation, or a complex organizational structure. It becomes politically problematic when opacity prevents informed consent, equal entry, or lawful oversight.', 'In Bayesian terms, camouflage changes the distribution of observed signals. The rival does not see the asset’s full option value and therefore prices the opportunity differently.'])
    page('6. Arbitrage and non-drawing states',['Arbitrage is the exploitation of a gap between valuations, prices, rights, or constraints. In a political economy setting, the gap may be between private and social value, incumbent and entrant access, or legal ownership and practical control.', 'A “non-drawing state” is a position in which the parties no longer have equivalent outside options. The policy question is whether that imbalance rewards productive discovery or merely reflects exclusion.'],[Image(str(ROOT/'entry_window.png'),width=6.8*inch,height=3.8*inch)])
    page('7. Network effects and standards',['Network effects make early adoption self-reinforcing: users value a service more when others use it. Standards can lower transaction costs, but a privately controlled standard can also become a gatekeeping device.', 'The OECD notes that network effects can reinforce digital-market concentration, while FTC materials emphasize that smaller platforms face particular entry challenges. These are institutional facts, not arguments that every large platform is unlawful.'])
    page('8. Property, law, and legitimacy',['Property rights are defined and enforced by public institutions. Secure tenure can support investment and development, while poorly designed or unequally enforced rights can reproduce exclusion.', 'A political-economy analysis therefore asks four questions: who can exclude, who can access, who can transfer, and who can challenge the allocation?'])
    page('9. A Bayesian game of entry',['Let the incumbent observe signal s_I and the entrant observe s_E. Each player forms beliefs over demand, regulation, and rival capability. Their probability spaces differ even when they face the same asset.', 'The first move changes both the state and the belief system. A later entrant may have better information but fewer available actions; an incumbent may have more control but a narrower legacy strategy.'])
    page('10. Model and propositions',['A compact model writes incumbent value as V_I = A + L + N + S − P, where A is asset control, L learning, N network effects, S switching costs, and P pioneering cost.', 'Proposition 1: first-mover advantage is durable only when at least one advantage is difficult to imitate. Proposition 2: camouflage increases the value of speed when signals are costly to interpret. Proposition 3: policy can preserve innovation while reducing lock-in by lowering switching and interoperability costs.'],[Preformatted('V_I = control + learning + network + switching − pioneering\nEntry succeeds when V_E − entry_cost > outside_option',ss['C'])])
    page('11. Cases and mechanisms',['Cases should be compared by mechanism rather than by industry label. Land, patents, operating systems, payment networks, scientific publication, and public infrastructure all involve different combinations of scarcity, learning, standards, and legal enforcement.', 'The same first move can be pro-competitive in one institutional setting and exclusionary in another. Context is not an escape from analysis; it is the analysis.'])
    page('12. Policy counterweights',['The main policy tools are open access, interoperability, portability, disclosure, public procurement rules, antitrust enforcement, land-tenure reform, and time-limited exclusivity.', 'Their common purpose is to keep early ownership from becoming unreviewable power. They do not require abolishing ownership or rewarding latecomers regardless of contribution.'],[Image(str(ROOT/'policy_levers.png'),width=6.8*inch,height=3.8*inch)])
    page('13. Measurement and evidence',['Claims about first-mover advantage require a counterfactual. Did the early owner create new value, or merely capture value that would have appeared anyway? Did network effects improve access, or raise switching costs? Did secrecy protect experimentation, or conceal an exclusionary practice?', 'Useful evidence includes entry rates, prices, quality, portability, innovation, ownership concentration, and outcomes for people excluded from the initial allocation.'])
    page('14. Implications for democratic political economy',['A democratic economy needs more than efficient allocation. It needs voice, contestability, exit, and the ability to revise rules when early decisions become harmful.', 'The keyhole should be widened where it hides rights or blocks meaningful challenge. The goal is not perfect symmetry; it is a justified asymmetry that remains accountable.'])
    page('Conclusion',['First movers often gain power because they do more than move first: they acquire options, shape standards, learn early, and influence the rules through which later actors must enter. Camouflage can preserve strategic flexibility; arbitrage can convert informational differences into control.', 'The political question is whether the resulting asymmetry remains contestable. A healthy system lets innovators keep rewards while preventing the keyhole from becoming a permanent lock.'])
    refs=['Markusen, J. (1990). First Mover Advantages, Blockaded Entry, and the Economics of Uneven Development. NBER Working Paper 3284. https://www.nber.org/papers/w3284','Dai, M., Jiang, Z., & Wang, N. (2022). Strategic Investment under Uncertainty with First- and Second-Mover Advantages. NBER Working Paper 30150. https://www.nber.org/papers/w30150','Katz, M. & Shapiro, C. (1985). Network externalities, competition, and compatibility. American Economic Review, 75(3), 424–440.','Katz, M. & Shapiro, C. (1986). Technology adoption in the presence of network externalities. Journal of Political Economy, 94(4), 822–841.','Coase, R. (1960). The problem of social cost. Journal of Law and Economics, 3, 1–44.','North, D. (1990). Institutions, Institutional Change and Economic Performance. Cambridge University Press.','Ostrom, E. (1990). Governing the Commons. Cambridge University Press.','Williamson, O. (1985). The Economic Institutions of Capitalism. Free Press.','Penrose, E. (1959). The Theory of the Growth of the Firm. Oxford University Press.','Teece, D. (1986). Profiting from innovation. Research Policy, 15(6), 285–305.','Arthur, W. B. (1989). Competing technologies, increasing returns, and lock-in. Economic Journal, 99(394), 116–131.','World Bank. Land and Property Research. https://www.worldbank.org/en/research/brief/land','World Bank. Land Governance Assessment Framework. https://www.worldbank.org/en/programs/land-governance-assessment-framework','OECD. Handbook on Competition Policy in the Digital Age. https://www.oecd.org/content/dam/oecd/en/publications/support-materials/2022/02/oecd-handbook-on-competition-policy-in-the-digital-age_50b6e951/oecd-handbook-on-competition-policy-in-the-digital-age-glossary-key-terms.pdf','OECD. Competition, regulation and growth in a digitized world (2023). https://www.oecd.org/content/dam/oecd/en/publications/reports/2023/03/competition-regulation-and-growth-in-a-digitized-world_6280b523/1b143a37-en.pdf','Federal Trade Commission. Anticompetitive Practices. https://www.ftc.gov/enforcement/anticompetitive-practices','Federal Trade Commission. Standard Setting in a Network Economy. https://www.ftc.gov/news-events/news/speeches/standard-setting-network-economy','Schelling, T. (1960). The Strategy of Conflict. Harvard University Press.','Akerlof, G. (1970). The market for “lemons.” Quarterly Journal of Economics, 84(3), 488–500.','Spence, M. (1973). Job market signaling. Quarterly Journal of Economics, 87(3), 355–374.','Stiglitz, J. (1985). Credit markets and the control of capital. Journal of Money, Credit and Banking, 17(2), 133–152.','Acemoglu, D. & Robinson, J. (2012). Why Nations Fail. Crown.','Mazzucato, M. (2013). The Entrepreneurial State. Anthem Press.','Sen, A. (1999). Development as Freedom. Oxford University Press.']
    story.append(P('Bibliography',ss['H'])); story.append(P('Sources span industrial organization, institutional economics, property rights, development, and competition policy.',ss['B']))
    for i,r in enumerate(refs,1): story.append(P(f'{i}. {r}',ss['S']))
    doc.build(story)

if __name__=='__main__': build()
