const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const C=require('./engine.js');
const values={left:'square',right:'square',seed:'42',rule:'wave',pattern:'random',threshold:'.30',speed:'5',yaw:'35',layers:'all',preset:'2d'};
const elements={};const ctx=new Proxy({},{get:()=>()=>{}});
const document={getElementById(id){return elements[id]??={value:values[id]||'',clientWidth:600,clientHeight:390,add(){},setAttribute(k,v){this[k]=v;},getContext(){return ctx;}};}};
const env={document,CellComplex:C,Option:function(text,value){this.value=value;},window:{devicePixelRatio:1,addEventListener(){}},requestAnimationFrame(){},performance:{now:()=>0}};
vm.createContext(env);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),env);
const read=expr=>vm.runInContext(expr,env);
for(let i=0;i<8;i++)elements.step.onclick();
assert.equal(read('generation'),8);
const saved=read('Array.from(fields[0].state)');
elements.right.value='tetra';elements.right.onchange();assert.equal(read('generation'),8);
assert.deepEqual(read('Array.from(fields[0].state)'),saved);
const m=C.mesh('tetra',5);let expected=C.initial(m,'random',42,'wave');for(let i=0;i<8;i++)expected=C.evolve(m,expected,'wave',.3).state;
assert.equal(read('Array.from(fields[1].state).join()'),[...expected].join());
assert.equal(read('history.length'),9);
elements.preset.value='3d';elements.preset.onchange();assert.equal(read('generation'),8);
elements.run.onclick();assert.equal(read('running'),true);
elements.preset.value='stretch';elements.preset.onchange();assert.equal(read('generation'),8);assert.equal(read('running'),false);
assert.equal(read('fields[0].state.join()'),read('fields[1].state.join()'));
elements.step.onclick();assert.equal(read('generation'),9);
for(let i=0;i<205;i++)elements.step.onclick();elements.right.value='triangle';elements.right.onchange();assert.equal(read('generation'),214);assert.equal(read('history.length'),200);
elements.reset.onclick();assert.equal(read('generation'),0);assert.equal(read('history.length'),1);
elements.step.onclick();elements.rule.value='cyclic';elements.rule.onchange();assert.equal(read('generation'),0);
console.log('Passed: consecutive steps, same-frame shape/preset switching, hidden geometry evolution, history retention/cap, pause-on-switch, explicit resets.');
