(()=>{'use strict';const $=id=>document.getElementById(id),canvas=$('map'),ctx=canvas.getContext('2d'),base=d3.geoMercator().scale(1).translate([0,0]),path=d3.geoPath(base).digits(8),cache=new Map(),pending=new Map(),failures=new Set(),stats={frames:0,visible:0};
const presets={world:{center:[0,15],zoom:1,title:'The whole world'},states:{center:[-84.9,32.6],zoom:38,title:'Georgia + Alabama'},atlanta:{center:[-84.388,33.749],zoom:260,title:'Metro Atlanta'},mobile:{center:[-88.0399,30.6954],zoom:350,title:'Metro Mobile'},arlington:{center:[-87.5886139,32.0570917],zoom:650,title:'Arlington, Alabama · Wilcox County'},hoover:{center:[-86.84,33.39],zoom:400,title:'Hoover / Cahaba River'},beltline:{center:[-84.390,33.762],zoom:1800,title:'BeltLine · imagined wildlife lane'}};
const coreBoxes={atlanta:[-84.47,33.68,-84.29,33.86],mobile:[-88.16,30.59,-87.96,30.79],arlington:[-87.80,31.88,-87.38,32.23]},metroBoxes={atlanta:[-85.4,32.7,-83.1,34.7],mobile:[-88.5,30.1,-87.9,31.4],arlington:[-88.0,31.65,-87.2,32.45]},stateBox=[-88.6,30,-80.7,35.1];
let view={...presets.world,center:[...presets.world.center]},selected=null,frame=false,timer=null,night=false,low=10,high=300,activeLayer='world',areaList=[],drag=null;
function normalize(g){if(!['Polygon','MultiPolygon'].includes(g.type))return g;const ps=g.type==='Polygon'?[g.coordinates]:g.coordinates,coords=ps.map(rings=>d3.geoArea({type:'Polygon',coordinates:rings})>2*Math.PI?rings.map(r=>[...r].reverse()):rings);return{type:g.type,coordinates:g.type==='Polygon'?coords[0]:coords};}
async function load(name){if(cache.has(name))return cache.get(name);if(pending.has(name))return pending.get(name);if(failures.has(name))return null;const promise=(async()=>{try{const r=await fetch('data/'+name+'.json');if(!r.ok)throw Error(name+': HTTP '+r.status);const a=await r.json();for(const f of a.features)f.feature={type:'Feature',geometry:normalize(f.geometry),properties:{}};cache.set(name,a);schedule();return a;}catch(e){failures.add(name);$('load').hidden=false;$('load').textContent='Some detail could not load. The coarse map remains usable. '+e.message;return null;}finally{pending.delete(name);if(!failures.size){$('load').hidden=pending.size===0;$('load').textContent='Loading finer map detail…';}}})();pending.set(name,promise);$('load').hidden=false;$('load').textContent=cache.size?'Loading finer map detail…':'Loading the coarse world layer…';return promise;}
function dimensions(){const w=canvas.clientWidth||900,h=canvas.clientHeight||600,s=w/(2*Math.PI)*view.zoom,c=base(view.center);return{w,h,s,tx:w/2-c[0]*s,ty:h/2-c[1]*s};}
function viewport(){const d=dimensions(),a=base.invert([(0-d.tx)/d.s,(d.h-d.ty)/d.s]),b=base.invert([(d.w-d.tx)/d.s,(0-d.ty)/d.s]);return[Math.max(-180,a[0]),Math.max(-85,a[1]),Math.min(180,b[0]),Math.min(85,b[1])];}
function getPath(f){if(!f.cachedPath){const s=path(f.feature);f.cachedPath=new Path2D(s||'');}return f.cachedPath;}
function visible(f,bounds){return WorldZones.bboxIntersects(f.bounds,bounds);}
function chosenLayers(){const bounds=viewport(),list=['world'];if(view.zoom>=20&&WorldZones.bboxIntersects(bounds,stateBox)&&cache.has('states'))list.push('states');if(view.zoom>=90&&WorldZones.bboxIntersects(bounds,stateBox)&&cache.has('tracts'))list.push('tracts');for(const key of Object.keys(metroBoxes)){if(view.zoom>=140&&WorldZones.bboxIntersects(bounds,metroBoxes[key])&&cache.has(key))list.push(key);if(view.zoom>=650&&WorldZones.bboxIntersects(bounds,coreBoxes[key])&&cache.has(key+'-core'))list.push(key+'-core');}return list;}
function schedule(){if(frame)return;frame=true;requestAnimationFrame(()=>{frame=false;draw();});}
function requestDetail(){clearTimeout(timer);timer=setTimeout(ensure,120);schedule();}
async function ensure(){const b=viewport(),jobs=[];if(view.zoom>=20&&WorldZones.bboxIntersects(b,stateBox)){jobs.push(load('states'));if(view.zoom>=90)jobs.push(load('tracts'));if($('water').checked||$('transport').checked||$('urban').checked)jobs.push(load('regional-geography'));}for(const key of Object.keys(metroBoxes)){if(view.zoom>=140&&WorldZones.bboxIntersects(b,metroBoxes[key]))jobs.push(load(key));if(view.zoom>=650&&WorldZones.bboxIntersects(b,coreBoxes[key])){jobs.push(load(key+'-core'));if($('water').checked||$('transport').checked)jobs.push(load(key+'-geography'));}}if($('water').checked)jobs.push(load('world-water'));if($('relief').checked)jobs.push(load('world-relief'));if($('transport').checked&&view.zoom>=6&&!WorldZones.bboxIntersects(b,stateBox))jobs.push(load('world-transport'));if($('urban').checked&&view.zoom>=6&&!WorldZones.bboxIntersects(b,stateBox))jobs.push(load('world-urban'));if($('proposal').checked)jobs.push(load('beltline'));await Promise.all(jobs);schedule();}
function drawFeatures(name,b,d,kindFilter=null){const a=cache.get(name);if(!a)return;for(const f of a.features){if(kindFilter&&!kindFilter(f.kind)||!visible(f,b))continue;const p=getPath(f);stats.visible++;if(['country','county','tract','blockgroup','block'].includes(f.kind)){ctx.fillStyle=WorldZones.colors[WorldZones.classify(f.density,low,high)];ctx.fill(p);ctx.strokeStyle='#62735c80';ctx.lineWidth=(f.kind==='country'?.6:.35)/d.s;ctx.stroke(p);}else{const colors={river:'#6da6bb',lake:'#bddbe3',mountain:'#c6c2af',urban:'#a9936e',road:'#ac9980',dirtroad:'#b49873',rail:'#747e7d',beltline:'#887197'};if(['lake','mountain','urban'].includes(f.kind)){ctx.fillStyle=colors[f.kind];ctx.globalAlpha=f.kind==='urban'?.32:.7;ctx.fill(p);ctx.globalAlpha=1;}else{ctx.strokeStyle=colors[f.kind]||'#80977c';ctx.lineWidth=(f.kind==='beltline'?2.5:f.kind==='river'?.9:.65)/d.s;ctx.setLineDash(f.kind==='rail'?[3/d.s,3/d.s]:[]);ctx.stroke(p);ctx.setLineDash([]);}}}}
function draw(){const d=dimensions(),ratio=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(d.w*ratio)||canvas.height!==Math.round(d.h*ratio)){canvas.width=Math.round(d.w*ratio);canvas.height=Math.round(d.h*ratio);}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle=night&&$('proposal').checked?'#dde5eb':'#e7f0f2';ctx.fillRect(0,0,d.w,d.h);stats.frames++;stats.visible=0;const b=viewport();ctx.save();ctx.translate(d.tx,d.ty);ctx.scale(d.s,d.s);const layers=chosenLayers();for(const key of layers)drawFeatures(key,b,d);activeLayer=layers.at(-1);const filter=k=>($('water').checked&&['river','lake'].includes(k))||($('transport').checked&&['road','rail','dirtroad'].includes(k))||($('urban').checked&&k==='urban')||($('relief').checked&&k==='mountain');if($('water').checked)drawFeatures('world-water',b,d,filter);if($('relief').checked)drawFeatures('world-relief',b,d,filter);if($('transport').checked&&view.zoom>=6)drawFeatures('world-transport',b,d,filter);if($('urban').checked&&view.zoom>=6)drawFeatures('world-urban',b,d,filter);if(view.zoom>=20)drawFeatures('regional-geography',b,d,filter);if(view.zoom>=650)for(const key of Object.keys(coreBoxes))if(WorldZones.bboxIntersects(b,coreBoxes[key]))drawFeatures(key+'-geography',b,d,filter);
if($('proposal').checked&&cache.has('beltline')){drawFeatures('beltline',b,d);ctx.strokeStyle=night?'#735989':'#a279bc';ctx.lineWidth=7/d.s;ctx.globalAlpha=.45;ctx.setLineDash([6/d.s,5/d.s]);for(const f of cache.get('beltline').features)if(visible(f,b))ctx.stroke(getPath(f));ctx.globalAlpha=1;ctx.setLineDash([]);if(view.zoom>1000){const icons=night?['🦝','🦉','🐢']:['🐦','🦌','🐢'],points=[[-84.368,33.771],[-84.41,33.75],[-84.388,33.8]];ctx.save();ctx.setTransform(ratio,0,0,ratio,0,0);points.forEach((c,i)=>{const p=base(c);ctx.font='23px serif';ctx.fillText(icons[i],p[0]*d.s+d.tx,p[1]*d.s+d.ty);});ctx.restore();}}
if(selected){ctx.strokeStyle='#74562f';ctx.lineWidth=2/d.s;ctx.stroke(getPath(selected));}ctx.restore();ctx.font='11px system-ui';ctx.fillStyle='#385749';ctx.textAlign='center';const labels=view.zoom<8?(cache.get('world')?.features||[]):[{name:'Atlanta',center:[-84.388,33.749]},{name:'Mobile',center:[-88.0399,30.6954]},{name:'Arlington',center:[-87.5886139,32.0570917]},{name:'Hoover / Cahaba',center:[-86.84,33.39]}];const used=[];for(const f of labels){const p=base(f.center),x=p[0]*d.s+d.tx,y=p[1]*d.s+d.ty;if(x<20||x>d.w-20||y<15||y>d.h-15||used.some(q=>Math.hypot(q[0]-x,q[1]-y)<45))continue;used.push([x,y]);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.strokeText(f.name,x,y);ctx.fillText(f.name,x,y);}const resolution=cache.get(activeLayer)?.resolution||'Country averages';$('resolution').textContent=resolution;$('scale').textContent=`~${Math.round(40075*Math.cos(view.center[1]*Math.PI/180)/view.zoom).toLocaleString()} km across`;$('map').setAttribute('aria-label',`${view.title}. ${resolution}. Population-derived scenario zones; not legal land-use or wildlife safety classifications.`);updateAreaList();}
function updateAreaList(){if(drag||pointers.size)return;const key=activeLayer+':'+view.title+':'+view.center.map(n=>n.toFixed(2)).join(':')+':'+view.zoom.toFixed(0);if($('areas').dataset.key===key)return;$('areas').dataset.key=key;const b=viewport();areaList=(cache.get(activeLayer)?.features||[]).filter(f=>visible(f,b)).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,500);$('areas').innerHTML='<option value="">Choose an area…</option>'+areaList.map((f,i)=>`<option value="${i}">${escape(f.name)}${f.id?' · '+f.id:''}</option>`).join('');}
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function inspect(f){selected=f;$('place-name').textContent=f.name;$('place-description').textContent=['Human-pressure candidate','Buffer candidate','Low-population candidate','Density unavailable'][WorldZones.classify(f.density,low,high)];$('facts').innerHTML=`<dt>Geographic unit</dt><dd>${escape(f.kind)}${f.id?' · '+escape(f.id):''}</dd><dt>Population</dt><dd>${f.people===null?'Not supplied':Number(f.people).toLocaleString()} · ${f.popYear||'2020 Census'}</dd><dt>Area denominator</dt><dd>${f.areaKm2?f.areaKm2.toLocaleString(undefined,{maximumFractionDigits:2})+' km²':'Not supplied'} · ${f.kind==='country'?'approximate mapped polygon':'Census land area'}</dd><dt>Average density</dt><dd>${f.density===null?'Unavailable':Number(f.density).toLocaleString(undefined,{maximumFractionDigits:2})+' people/km²'}</dd><dt>Interpretation</dt><dd>An area average, not a household location, habitat survey, or guarantee of wilderness.</dd>`;schedule();}
$('areas').onchange=()=>{if($('areas').value!=='')inspect(areaList[Number($('areas').value)]);};
function focus(key){view={...presets[key],center:[...presets[key].center]};selected=null;$('place-name').textContent=view.title;$('facts').innerHTML='';$('place-description').textContent=key==='arlington'?'Arlington is a community in Wilcox County. Click a Census unit to inspect its population average.':key==='beltline'?'The wildlife lane is imagined; the trail alignments and underlying Census geography are sourced. Click an area to inspect its average.':'Click a geographic unit for its source population, area, and average density.';$('view-title').textContent=view.title;for(const b of document.querySelectorAll('[data-place]'))b.setAttribute('aria-pressed',String(b.dataset.place===key));if(key==='beltline'){$('proposal').checked=true;$('water').checked=true;$('transport').checked=true;}$('beltline-panel').hidden=!$('proposal').checked;requestDetail();}
for(const b of document.querySelectorAll('[data-place]'))b.onclick=()=>focus(b.dataset.place);$('in').onclick=()=>{view.zoom=Math.min(5000,view.zoom*1.5);requestDetail();};$('out').onclick=()=>{view.zoom=Math.max(1,view.zoom/1.5);requestDetail();};$('reset-view').onclick=()=>focus(Object.keys(presets).find(k=>presets[k].title===view.title)||'world');
for(const key of['water','transport','relief','urban','proposal'])$(key).onchange=()=>{$('beltline-panel').hidden=!$('proposal').checked;ensure();schedule();};
for(const key of['low','high'])$(key).oninput=()=>{try{const l=Number($('low').value),h=Number($('high').value);WorldZones.classify(0,l,h);low=l;high=h;$('model-error').textContent='';if(selected)inspect(selected);schedule();}catch(e){$('model-error').textContent=e.message;}};
$('time').onclick=()=>{night=!night;$('time').textContent=night?'Night → Day':'Day → Night';$('wildlife-story').textContent=night?'Raccoons exploring the dark edges. Owls over the canopy. Quiet water pockets for the smaller residents. The wildlife lane follows a different rhythm from the human trail.':'Birds over the canopy. Turtles beside little ponds. Deer, lizards, snakes, fish, crawdads, and salamanders in an imagined mosaic of native habitat.';$('wildlife-icons').textContent=night?'🦝 🦉 🐢 🐟':'🐦 🦌 🐢 🦎 🐍 🐟';schedule();};
function coords(e){const r=canvas.getBoundingClientRect(),d=dimensions();return base.invert([(e.clientX-r.left-d.tx)/d.s,(e.clientY-r.top-d.ty)/d.s]);}
function pick(c){for(const key of chosenLayers().reverse()){const hit=(cache.get(key)?.features||[]).find(f=>c[0]>=f.bounds[0]&&c[0]<=f.bounds[2]&&c[1]>=f.bounds[1]&&c[1]<=f.bounds[3]&&d3.geoContains(f.feature,c));if(hit)return hit;}return null;}
const pointers=new Map();let pinch=null;canvas.onpointerdown=e=>{pointers.set(e.pointerId,[e.clientX,e.clientY]);canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const a=[...pointers.values()];pinch={distance:Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]),zoom:view.zoom};drag=null;}else drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};};canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2&&pinch){const a=[...pointers.values()],distance=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);view.zoom=Math.max(1,Math.min(5000,pinch.zoom*distance/Math.max(1,pinch.distance)));requestDetail();return;}if(!drag)return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4)drag.moved=true;if(drag.moved){const d=dimensions(),c=base(view.center);view.center=base.invert([c[0]-(e.clientX-drag.x)/d.s,c[1]-(e.clientY-drag.y)/d.s]);view.center[0]=Math.max(-180,Math.min(180,view.center[0]));view.center[1]=Math.max(-80,Math.min(80,view.center[1]));canvas.classList.add('dragging');requestDetail();}drag.x=e.clientX;drag.y=e.clientY;};canvas.onpointerup=e=>{if(drag&&!drag.moved){const f=pick(coords(e));if(f)inspect(f);}pointers.delete(e.pointerId);drag=null;pinch=null;canvas.classList.remove('dragging');schedule();};canvas.onpointercancel=e=>{pointers.delete(e.pointerId);drag=null;pinch=null;};canvas.onwheel=e=>{e.preventDefault();const before=coords(e);view.zoom=Math.max(1,Math.min(5000,view.zoom*(e.deltaY<0?1.18:.85)));const after=coords(e);view.center[0]+=before[0]-after[0];view.center[1]=Math.max(-80,Math.min(80,view.center[1]+before[1]-after[1]));requestDetail();};canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();const step=30/view.zoom;if(e.key==='ArrowLeft')view.center[0]-=step;if(e.key==='ArrowRight')view.center[0]+=step;if(e.key==='ArrowUp')view.center[1]+=step;if(e.key==='ArrowDown')view.center[1]-=step;if(e.key==='+')view.zoom=Math.min(5000,view.zoom*1.4);if(e.key==='-')view.zoom=Math.max(1,view.zoom/1.4);view.center[1]=Math.max(-80,Math.min(80,view.center[1]));requestDetail();};new ResizeObserver(schedule).observe(canvas);
window.LionLambWorld={focus,snapshot:()=>({view:{...view,center:[...view.center]},loaded:[...cache.keys()],pending:[...pending.keys()],failures:[...failures],activeLayer,selected:selected?{name:selected.name,id:selected.id,density:selected.density,people:selected.people}:null,thresholds:{low,high},night,stats:{...stats}}),inspectAt:c=>{const f=pick(c);if(f)inspect(f);return f?{name:f.name,id:f.id,kind:f.kind}:null;},project:c=>{const d=dimensions(),p=base(c);return[p[0]*d.s+d.tx,p[1]*d.s+d.ty];},ready:async()=>{await Promise.all([...pending.values()]);}};
load('world').then(()=>{schedule();ensure();});})();
