'use strict';
const {cards,themes}=AtlasData,$=id=>document.getElementById(id);let trail=-1,selected=0,result;
const shapes={practice:'○',text:'△',object:'□'};
function renderCards(){const q=$('search').value.toLowerCase();const list=cards.filter(c=>(trail<0||c.themes[trail])&&[c.name,c.place,c.fact,c.deep,...themes.filter((t,i)=>c.themes[i]).map(t=>t.name)].join(' ').toLowerCase().includes(q));$('count').textContent=`${list.length} of ${cards.length} starting points`;$('cards').innerHTML=list.map(c=>`<article><span class="food-icon" aria-hidden="true">${c.icon}</span><span class="kind">${shapes[c.kind]} ${c.kind} · ${c.era}</span><h3>${c.name}</h3><span class="place">${c.flag} ${c.place}</span><p>${c.fact}</p><a href="${c.url}">${c.source} ↗</a><details><summary>Look closer 🔎</summary><p>${c.deep}</p><p><b>Wonder together:</b> ${c.question}</p></details><button data-card="${c.id}">Find its connections ↗</button></article>`).join('')||'<p>No matches yet. Try another word or choose all trails.</p>';document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{selected=cards.findIndex(c=>c.id===b.dataset.card);draw();$('focus').scrollIntoView({block:'center'});});}
function draw(){const t=+$('theme').value;result=AtlasEngine.run(cards,{triangles:$('triangles').checked});const coords=cards.map((c,i)=>[320+235*Math.cos(i*Math.PI/4-Math.PI/2),235+175*Math.sin(i*Math.PI/4-Math.PI/2)]);let svg='';for(const f of result.simplices)if(f.theme===t&&$('triangles').checked)svg+=`<polygon points="${f.nodes.map(i=>coords[i].join(',')).join(' ')}" fill="#c3b6ff" opacity=".16"/>`;for(const e of result.edges)if(e.themes.includes(t)){const a=coords[e.a],b=coords[e.b];svg+=`<line class="edge" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`;}
svg+=`<text x="320" y="230" text-anchor="middle">${themes[t].icon} ${themes[t].name}</text><text x="320" y="254" text-anchor="middle">a theme becomes our focus</text>`;
cards.forEach((c,i)=>{const [x,y]=coords[i],fill=c.themes[t]?themes[t].color:'#53647a';const shape=c.kind==='practice'?'<circle r="24"/>':c.kind==='text'?'<path d="M0 -28L27 22H-27Z"/>':'<rect x="-23" y="-23" width="46" height="46" rx="4"/>';svg+=`<g class="node" data-node="${i}" transform="translate(${x},${y})"><g fill="${fill}" stroke="${i===selected?'#fff':'#152238'}" stroke-width="${i===selected?4:2}">${shape}</g><text text-anchor="middle" y="7" style="font-size:24px">${c.icon}</text><text text-anchor="middle" y="46">${i+1}</text></g>`;});$('map').innerHTML=svg;document.querySelectorAll('[data-node]').forEach(e=>e.onclick=()=>{selected=+e.dataset.node;draw();});$('map-buttons').innerHTML=cards.map((c,i)=>`<button data-select="${i}" aria-pressed="${i===selected}">${i+1}. ${c.name}</button>`).join('');document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selected=+b.dataset.select;draw();});const c=cards[selected];const related=result.edges.filter(e=>e.themes.includes(t)&&(e.a===selected||e.b===selected)).map(e=>cards[e.a===selected?e.b:e.a].name);$('focus').innerHTML=`<span class="food-icon">${c.icon}</span><h3>${c.name}</h3><p>${c.fact}</p><p><b>Along this trail:</b> ${related.length?related.join(' · '):'No authored connection on this trail yet. Try another theme.'}</p><p>${c.question}</p><a href="${c.url}">Meet the source ↗</a>`;$('trace').textContent=`${result.edges.length} pairwise links · 3 theme hubs · ${$('triangles').checked?result.simplices.length:0} active triangle · ${result.iterations} iterations · ${result.converged?'settled numerically':'iteration limit reached'}.`; $('scores').innerHTML=cards.map((c,i)=>`<div class="score"><span>${c.name}</span><label>${Math.round(result.strengths[i][t]*100)} / 100 theme affinity <meter min="0" max="1" value="${result.strengths[i][t]}">${result.strengths[i][t]}</meter></label></div>`).join('');}
$('filters').innerHTML=[{name:'✨ All trails'},...themes].map((t,i)=>`<button data-trail="${i-1}" aria-pressed="${i===0}">${t.icon||''} ${t.name}</button>`).join('');document.querySelectorAll('[data-trail]').forEach(b=>b.onclick=()=>{trail=+b.dataset.trail;document.querySelectorAll('[data-trail]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderCards();});$('search').oninput=renderCards;$('theme').onchange=draw;$('triangles').onchange=draw;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{$('feedback').textContent=b.dataset.answer==='0'?'🌟 Yes! A shared theme is something we can compare. Influence and historical identity need additional evidence.':'🌱 That needs more evidence. A shared hospitality theme is supported; the same event or direct copying does not follow from similarity alone.';});renderCards();draw();

$("tree").innerHTML=themes.map((t,i)=>`<details><summary>${t.icon} ${t.name}</summary><ul>${cards.filter(c=>c.themes[i]).map(c=>`<li>${shapes[c.kind]} ${c.name} · <a href="${c.url}">${c.source}</a></li>`).join("")}</ul></details>`).join("");
