/* Curated source summaries, checked 2026-09-26. Themes are editorial reading aids. */
(function(root){
const cards=[
{id:'sisters',name:'The Three Sisters',icon:'🌽',kind:'practice',place:'Haudenosaunee · northeastern North America',flag:'',era:'Living agricultural knowledge',themes:[1,0,1],fact:'Corn, beans, and squash are known together as the Three Sisters in Haudenosaunee agriculture.',deep:'A planting system connects several crops. This is one named tradition within the many food traditions of Indigenous North America.',question:'What can three different plants contribute to a shared garden?',source:'New York State Museum',url:'https://www.nysm.nysed.gov/mohawk-haudenosaunee-village/three-sisters-diorama'},
{id:'couscous',name:'Couscous connections',icon:'🍲',kind:'practice',place:'Algeria · Mauritania · Morocco · Tunisia',flag:'🇩🇿 🇲🇷 🇲🇦 🇹🇳',era:'Living culinary heritage',themes:[1,1,0],fact:'The knowledge and practices of making and sharing couscous have a joint UNESCO heritage inscription involving four countries.',deep:'Heritage recognition concerns people’s knowledge and practices, not just the food on a plate. A shared dish can have many local versions.',question:'How can the same dish feel familiar and different in two homes?',source:'UNESCO',url:'https://ich.unesco.org/en/RL/knowledge-know-how-and-practices-pertaining-to-the-production-and-consumption-of-couscous-01602'},
{id:'kimjang',name:'A season for sharing',icon:'🥬',kind:'practice',place:'Republic of Korea',flag:'🇰🇷',era:'Living culinary heritage',themes:[1,1,1],fact:'Kimjang is the making and sharing of kimchi in the Republic of Korea, recognized by UNESCO as living cultural heritage.',deep:'Culinary anthropology asks about the work, knowledge, and relationships surrounding food. Here the source names sharing as part of the practice itself.',question:'What changes when preparing food becomes a team activity?',source:'UNESCO',url:'https://ich.unesco.org/en/RL/kimjang-making-and-sharing-kimchi-in-the-republic-of-korea-00881'},
{id:'bunya',name:'Gathering around bunya',icon:'🌲',kind:'practice',place:'Aboriginal peoples · Bunya Mountains and neighboring regions',flag:'',era:'Traditional gathering histories',themes:[1,1,1],fact:'Aboriginal hosts in the Bunya Mountains and Blackall Ranges invited people from other regions to gatherings around bunya harvests.',deep:'Queensland Parks describes harvest protocols and invitations across a wide area. This regional account does not stand for every Aboriginal nation.',question:'How can the season of a tree help people plan a gathering?',source:'Queensland Parks',url:'https://parks.qld.gov.au/parks/bunya-mountains/about/culture'},
{id:'genesis',name:'Welcome under a tree',icon:'🍞',kind:'text',place:'Genesis 18:1–8 · Hebrew Bible',flag:'',era:'Ancient religious narrative',themes:[1,1,0],fact:'In Genesis 18, Abraham welcomes three visitors, asks Sarah to prepare bread, and offers a meal beneath a tree.',deep:'This card describes what the passage says. Comparing its hospitality theme with another story does not establish a shared historical event.',question:'Which small acts make a visitor feel welcome?',source:'Genesis 18:1–8, KJV',url:'https://www.biblegateway.com/passage/?search=Genesis+18%3A1-8&version=KJV'},
{id:'odyssey',name:'A meal for a traveler',icon:'⛵',kind:'text',place:'Homer’s Odyssey · Book 6',flag:'',era:'Ancient Greek epic',themes:[1,1,0],fact:'In Book 6 of the Odyssey, Nausicaa asks her companions to give a stranded traveler food and drink.',deep:'The literary scene is a useful comparison with Genesis for the theme of welcome. Similarity alone does not show which story influenced another.',question:'What might a tired traveler need before telling their story?',source:'Perseus Digital Library · A. T. Murray translation',url:'https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0136%3Abook%3D6'},
{id:'bread',name:'A loaf across time',icon:'🥖',kind:'object',place:'Deir el-Bahri · ancient Egypt',flag:'',era:'New Kingdom · museum object',themes:[1,0,0],fact:'The Metropolitan Museum of Art preserves a piece of bread excavated from a foundation deposit at the tomb of Senenmut in Egypt.',deep:'An actual object and a written story are different kinds of evidence. Both can open questions about food, but they answer different questions.',question:'What could an old loaf tell us that a story could not?',source:'The Metropolitan Museum of Art · Bread',url:'https://www.metmuseum.org/art/collection/search/548945'},
{id:'wampum',name:'Patterns that remember',icon:'🐚',kind:'object',place:'Haudenosaunee Confederacy',flag:'',era:'Traditional knowledge · continuing practice',themes:[0,1,0],fact:'The Haudenosaunee Confederacy explains that wampum belts help narrate history, traditions, and laws. The Hiawatha Belt conveys the unity of five nations.',deep:'The belt’s connected shapes carry a particular meaning. Our atlas triangles are a separate learning diagram, not a replacement for that tradition.',question:'How can a pattern help people remember a relationship?',source:'Haudenosaunee Confederacy · Wampum',url:'https://www.haudenosauneeconfederacy.com/wampum/'}
];
const themes=[{id:'food',name:'Food & making',icon:'🍲',color:'#75dce8'},{id:'welcome',name:'Welcome & connection',icon:'🤝',color:'#c3b6ff'},{id:'land',name:'Land & seasons',icon:'🌱',color:'#94e3c0'}];
root.AtlasData={cards,themes};if(typeof module!=='undefined')module.exports=root.AtlasData;
})(globalThis);
