(()=>{'use strict';
const $=s=>document.querySelector(s),icons={R:'♜',B:'♝',N:'♞',Q:'♛',K:'♚',P:'♟'},countryById=new Map();let data=null,selected=null,city=null,preview=[],token=null,total=0,ledger=[],jewels=new Set(),panes=[],renderPending=false,saved=null;
try{saved=JSON.parse(localStorage.getItem('worlds-of-kings-earth-v1')||'null');}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('worlds-of-kings-earth-v1',JSON.stringify({selected,token,total,ledger:ledger.slice(-40),jewels:[...jewels]}));}catch{}}
function feature(g){
// Small rounded coastal rings can have reversed spherical winding.
// Each mapped administrative area occupies less than a hemisphere.
const coordinates=g.type==='Polygon'?[g.coordinates]:g.coordinates;
const polygons=coordinates.map(rings=>d3.geoArea({type:'Polygon',coordinates:rings})>2*Math.PI?rings.map(r=>[...r].reverse()):rings);
return{type:'Feature',properties:{},geometry:{type:g.type,coordinates:g.type==='Polygon'?polygons[0]:polygons}};
}
function countryColor(code){let hash=0;for(const ch of code||'')hash=(hash*31+ch.charCodeAt(0))>>>0;return`hsl(${35+hash%115} 28% ${80+hash%9}%)`;}
function boundsContains(extent,lon,lat){return lon>=extent[0]-.001&&lon<=extent[2]+.001&&lat>=extent[1]-.001&&lat<=extent[3]+.001;}
function locate(lon,lat){const hits=data.regions.filter(r=>boundsContains(r.extent,lon,lat));return hits.find(r=>d3.geoContains(r.feature,[lon,lat]))?.id;}
function focusPlace(center,zoom=1.8,pane=panes[0]){if(!pane)return;pane.lon=center[0];pane.lat=center[1];pane.zoom=zoom;pane.mode='globe';pane.el.querySelector('select').value='globe';schedule();}
function focusRegion(id){const r=data.regions[id];const span=Math.max(r.extent[2]-r.extent[0],r.extent[3]-r.extent[1]);focusPlace(r.center,Math.min(50,Math.max(1.3,55/Math.max(1,span))));}
function selectRegion(id,recenter=false){if(!data.regions[id])return;selected=id;const r=data.regions[id],country=countryById.get(r.country);$('#selection').hidden=false;$('#place-title').textContent=r.name;$('#place-meta').textContent=r.country?`${country?.name||r.country} · ${r.kind==='province'?'mapped administrative area':'country fallback; no province data supplied'}`:'Ocean grid space · coastline-clipped water area';$('#place-facts').innerHTML=`<dt>Anchor coordinates</dt><dd>${Math.abs(r.center[1]).toFixed(3)}°${r.center[1]>=0?'N':'S'}, ${Math.abs(r.center[0]).toFixed(3)}°${r.center[0]>=0?'E':'W'}</dd><dt>Mapped border connections</dt><dd>${r.neighbors.length}${!r.neighbors.length?' · isolated or unresolved at this map tolerance':''}</dd>${country?`<dt>Country’s mapped land spaces</dt><dd>${country.spaces.length}${country.spaces.length<16?' · supplemental city-area design needed before full-army deployment':''}</dd>`:''}`;$('#neighbors').innerHTML=r.neighbors.map(n=>`<li><button data-region="${n}">${esc(data.regions[n].name)}</button></li>`).join('');for(const b of $('#neighbors').querySelectorAll('button'))b.onclick=()=>selectRegion(Number(b.dataset.region),true);refreshPreview();if(recenter)focusRegion(id);save();}
function refreshPreview(){if(selected===null)return;const type=$('#piece').value,heading=Number($('#heading').value);$('#heading-label').hidden=type!=='P';preview=EarthAtlas.routes(data,selected,type,heading);$('#destination').innerHTML=preview.map(m=>`<option value="${m.to}">${esc(data.regions[m.to].name)} · ${m.kind}</option>`).join('');$('#compass').innerHTML=data.regions[selected].routes.map((arr,d)=>`<div><strong>${EarthAtlas.directions[d]}</strong><span>${arr.length?arr.map(n=>esc(data.regions[n].name)).join(' / '):'No candidate in this sector'}</span></div>`).join('');$('#token-status').textContent=token===null?'An exploration token records routes and travel, without starting a match.':token===selected?`${preview.length} candidate destinations from your token’s space.`:`Token is in ${data.regions[token].name}; place it here to start a new route.`;$('#travel').disabled=token!==selected||!preview.length;$('#distance').textContent=`${Math.round(total).toLocaleString()} km travelled along candidate routes`;$('#ledger').innerHTML=ledger.slice(-20).reverse().map(x=>`<li>${esc(x)}</li>`).join('');schedule();}
function travel(to){if(token!==selected)return;const m=preview.find(m=>m.to===to);if(!m)return;const km=EarthAtlas.journeyDistance(data,selected,m.path);ledger.push(`${icons[$('#piece').value]} ${data.regions[selected].name} → ${data.regions[to].name} · ${Math.round(km).toLocaleString()} km`);total+=km;token=to;if($('#piece').value==='P')$('#heading').value=String(m.dir);selectRegion(to);save();}
$('#piece').onchange=refreshPreview;$('#heading').onchange=refreshPreview;$('#token').onclick=()=>{token=selected;ledger.push(`Journey begins in ${data.regions[selected].name}.`);refreshPreview();save();};$('#travel').onclick=()=>{if($('#destination').value!=='')travel(Number($('#destination').value));};$('#clear-travel').onclick=()=>{token=null;total=0;ledger=[];refreshPreview();save();};
function selectCity(c){city=c;$('#city-panel').hidden=false;$('#city-title').textContent=`${c.name}${jewels.has(c.key)?' 👑':''}`;$('#crown').textContent=jewels.has(c.key)?'Remove this honorary crown':'Crown this hometown 👑';const n=locate(...c.center);if(n!==undefined)selectRegion(n);focusPlace(c.center,8);$('#hover').textContent=`${c.name} · ${countryById.get(c.country)?.name||c.country}${c.capital?' · capital':''} · source population estimate ${Number(c.population).toLocaleString()}`;}
$('#crown').onclick=()=>{if(!city)return;if(jewels.has(city.key))jewels.delete(city.key);else jewels.add(city.key);save();$('#city-title').textContent=`${city.name}${jewels.has(city.key)?' 👑':''}`;$('#crown').textContent=jewels.has(city.key)?'Remove this honorary crown':'Crown this hometown 👑';schedule();};
$('#search').oninput=()=>{if(!data)return;const q=$('#search').value.trim().toLocaleLowerCase(),list=[];if(q.length<2){$('#results').hidden=true;return;}const match=(a,b='')=>a.toLocaleLowerCase().includes(q)||b.toLocaleLowerCase().includes(q);for(const c of data.countries)if(match(c.name,c.formal))list.push({kind:'country',value:c,name:c.name});for(const r of data.regions)if(r.country&&match(r.name,r.local))list.push({kind:'province',value:r,name:`${r.name} · ${countryById.get(r.country)?.name||r.country}`});for(const c of data.cities)if(match(c.name,c.local))list.push({kind:'city',value:c,name:`${c.name} · ${countryById.get(c.country)?.name||c.country}`});const results=list.slice(0,24);$('#results').hidden=false;$('#results').innerHTML=results.length?results.map((r,i)=>`<button data-result="${i}">${esc(r.name)} <small>(${r.kind})</small></button>`).join(''):'<p>No name matches in this source snapshot.</p>';for(const b of $('#results').querySelectorAll('button'))b.onclick=()=>{const r=results[Number(b.dataset.result)];$('#results').hidden=true;$('#search').value=r.value.name;if(r.kind==='city')selectCity(r.value);else if(r.kind==='province')selectRegion(r.value.id,true);else{const c=r.value;selectRegion(c.spaces[0]);$('#place-title').textContent=c.name;$('#place-meta').textContent=`${c.spaces.length} mapped land spaces · choose a province on the globe`;focusPlace(c.center,2);}};};
function layers(){return{countries:$('#country-labels').checked,provinces:$('#province-labels').checked,cities:$('#city-labels').checked,capitals:$('#capital-labels').checked,local:$('#local-labels').checked,ocean:$('#ocean-grid').checked,grid:$('#graticule').checked,jewels:$('#jewels').checked};}for(const c of document.querySelectorAll('.toggle input'))c.onchange=schedule;
function projection(p,w,h){let proj;if(p.mode==='globe')proj=d3.geoOrthographic().rotate([-p.lon,-p.lat]).clipAngle(90).scale(Math.min(w,h)*.43*p.zoom);else if(p.mode==='mercator')proj=d3.geoMercator().rotate([-p.lon,0]).scale(w*.145*p.zoom);else proj=d3.geoRobinson().rotate([-p.lon,0]).scale(Math.min(w*.165,h*.275)*p.zoom);return proj.translate([w/2,h/2]).clipExtent([[0,0],[w,h]]).precision(.7);}
function draw(p){if(!data)return;const canvas=p.canvas,w=canvas.clientWidth||700,h=canvas.clientHeight||500,dpr=Math.min(2,devicePixelRatio||1),ctx=canvas.getContext('2d');if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#f1f7f8';ctx.fillRect(0,0,w,h);p.proj=projection(p,w,h);const path=d3.geoPath(p.proj,ctx),flags=layers(),sphere={type:'Sphere'};ctx.beginPath();path(sphere);ctx.fillStyle='#cce7f1';ctx.fill();ctx.strokeStyle='#8eb7c7';ctx.lineWidth=.8;ctx.stroke();if(p.mode==='globe'){ctx.save();ctx.beginPath();path(sphere);ctx.clip();}
if(flags.ocean){for(const r of data.ocean){ctx.beginPath();path(r.feature);ctx.fillStyle=(r.row+r.col)%2?'#d8edf5':'#cce7f1';ctx.fill();ctx.strokeStyle='#679aac40';ctx.lineWidth=.45;ctx.stroke();}}
for(const r of data.land){ctx.beginPath();path(r.feature);ctx.fillStyle=countryColor(r.country);ctx.fill();ctx.strokeStyle='#617a6540';ctx.lineWidth=p.zoom>4?.7:.3;ctx.stroke();}
for(const c of data.countries){ctx.beginPath();path(c.feature);ctx.strokeStyle='#526c678c';ctx.lineWidth=.75;ctx.stroke();}
if(flags.grid){ctx.beginPath();path(d3.geoGraticule().step([12,12])());ctx.strokeStyle='#668fa540';ctx.lineWidth=.5;ctx.stroke();}
if(selected!==null){ctx.beginPath();path(data.regions[selected].feature);ctx.fillStyle='#ffdc7870';ctx.fill();ctx.strokeStyle='#a77213';ctx.lineWidth=1.8;ctx.stroke();for(const m of preview){ctx.beginPath();path(data.regions[m.to].feature);ctx.fillStyle=m.kind==='capture direction'?'#b84d3660':'#24b89555';ctx.fill();}const destination=Number($('#destination').value);const active=preview.find(m=>m.to===destination);if(active){ctx.beginPath();path({type:'LineString',coordinates:[data.regions[selected].center,...active.path.map(n=>data.regions[n].center)]});ctx.strokeStyle=active.kind==='capture direction'?'#b84d36':'#16876f';ctx.lineWidth=2;ctx.setLineDash(active.kind==='jump'?[5,4]:[]);ctx.stroke();ctx.setLineDash([]);}}
const visible=coord=>{if(p.mode==='globe'&&d3.geoDistance([p.lon,p.lat],coord)>Math.PI/2-.015)return null;if(p.mode==='mercator'&&Math.abs(coord[1])>85)return null;const pt=p.proj(coord);return pt&&Number.isFinite(pt[0])&&pt[0]>=0&&pt[0]<=w&&pt[1]>=0&&pt[1]<=h?pt:null;};const labels=[];function label(text,coord,color='#233f48',priority=false,marker=false){const pt=visible(coord);if(!pt)return;ctx.font=`${priority?'600 ':''}${priority?12:10}px system-ui`;const tw=ctx.measureText(text).width,rect={x:pt[0]-tw/2-3,y:pt[1]-14,w:tw+6,h:17};if(!priority&&labels.some(r=>r.x<rect.x+rect.w&&r.x+r.w>rect.x&&r.y<rect.y+rect.h&&r.y+r.h>rect.y))return;labels.push(rect);ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.strokeStyle='#ffffff';ctx.lineWidth=3.5;ctx.strokeText(text,pt[0],pt[1]-3);ctx.fillStyle=color;ctx.fillText(text,pt[0],pt[1]-3);if(marker){ctx.beginPath();ctx.arc(pt[0],pt[1],2,0,Math.PI*2);ctx.fill();}}
if(flags.jewels)for(const c of data.cities)if(jewels.has(c.key))label(`👑 ${flags.local?c.local:c.name}`,c.center,'#714b15',true,true);
if(flags.countries){for(const c of data.countries)label(c.name,c.center,'#233f48');}
if(flags.provinces&&p.zoom>2.2){for(const r of data.land)label(flags.local?r.local:r.name,r.center,'#324d43');}
let cityCount=0;for(const c of data.cities){if(!(flags.capitals&&c.capital||flags.cities&&(p.zoom>3||c.population>3000000)))continue;if(cityCount>140)break;if(visible(c.center)){label(flags.local?c.local:c.name,c.center,'#244b61',false,true);cityCount++;}}
for(const[lon,lat,name]of[[-145,10,'PACIFIC'],[-30,10,'ATLANTIC'],[75,-20,'INDIAN'],[0,82,'ARCTIC'],[0,-62,'SOUTHERN']])label(name,[lon,lat],'#426d85');
if(token!==null){const pt=visible(data.regions[token].center);if(pt){ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='25px serif';ctx.strokeStyle='#17364b';ctx.lineWidth=3;ctx.strokeText(icons[$('#piece').value],pt[0],pt[1]);ctx.fillStyle='#fff0b5';ctx.fillText(icons[$('#piece').value],pt[0],pt[1]);}}
if(p.mode==='globe')ctx.restore();ctx.fillStyle='#4e6c79';ctx.font='10px system-ui';ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillText(p.mode==='mercator'?'Mercator · polar view clipped · switch to globe for poles':'Drag to explore · zoom for more names · click to inspect',12,h-12);}
function schedule(){if(renderPending)return;renderPending=true;requestAnimationFrame(()=>{renderPending=false;panes.forEach(draw);});}
function hit(p,e){if(!p.proj)return null;const r=p.canvas.getBoundingClientRect(),xy=[e.clientX-r.left,e.clientY-r.top],coord=p.proj.invert(xy);if(!coord||!coord.every(Number.isFinite))return null;if(p.mode==='globe'){const rr=Math.min(r.width,r.height)*.43*p.zoom;if(Math.hypot(xy[0]-r.width/2,xy[1]-r.height/2)>rr)return null;}return{coord,region:locate(...coord)};}
function createPane(i){const el=document.createElement('section');el.className='pane';el.setAttribute('aria-label',`Earth view ${i+1}`);el.innerHTML=`<div class="pane-tools"><span>VIEW ${i+1}</span><select aria-label="Projection for view ${i+1}"><option value="globe">3D globe</option><option value="mercator">Mercator</option><option value="robinson">Robinson</option></select><button data-action="home">World</button><button data-action="selected">Focus</button><details class="view-more"><summary>More</summary><div><button data-action="north" title="North Pole">N↑</button><button data-action="south" title="South Pole">S↓</button><button data-action="opposite" title="Opposite side">↔</button></div></details><button data-action="in" aria-label="Zoom in">+</button><button data-action="out" aria-label="Zoom out">−</button></div><canvas role="img" aria-label="Real-world globe showing provinces, cities, ocean cells, and selected candidate routes"></canvas>`;$('#panes').append(el);const p={el,canvas:el.querySelector('canvas'),mode:'globe',lon:i===1?130:-35,lat:i===2?90:i===3?-90:20,zoom:1,proj:null};el.querySelector('select').onchange=e=>{p.mode=e.target.value;p.zoom=1;if(p.mode!=='globe')p.lon=0;schedule();};for(const b of el.querySelectorAll('button'))b.onclick=()=>{switch(b.dataset.action){case'home':p.lon=-35;p.lat=20;p.zoom=1;break;case'selected':if(selected!==null){const r=data.regions[selected];p.lon=r.center[0];p.lat=r.center[1];p.zoom=3;}break;case'north':p.lat=90;p.zoom=1.3;p.mode='globe';el.querySelector('select').value='globe';break;case'south':p.lat=-90;p.zoom=1.3;p.mode='globe';el.querySelector('select').value='globe';break;case'opposite':p.lon+=180;p.lat=-p.lat;break;case'in':p.zoom=Math.min(80,p.zoom*1.4);break;case'out':p.zoom=Math.max(.6,p.zoom/1.4);break;}schedule();};let drag=null;
p.canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false};p.canvas.setPointerCapture(e.pointerId);};p.canvas.onpointermove=e=>{if(drag){if(Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy)>5)drag.moved=true;if(drag.moved){p.lon-=(e.clientX-drag.x)*.4/p.zoom;if(p.mode==='globe')p.lat=Math.max(-90,Math.min(90,p.lat+(e.clientY-drag.y)*.4/p.zoom));schedule();}drag.x=e.clientX;drag.y=e.clientY;return;}const h=hit(p,e);if(h?.region!==undefined&&h?.region!==null){const r=data.regions[h.region];$('#hover').textContent=`${r.name}${r.country?' · '+countryById.get(r.country)?.name:''} · ${h.coord[1].toFixed(2)}° latitude, ${h.coord[0].toFixed(2)}° longitude`;}};p.canvas.onpointerup=e=>{if(drag&&!drag.moved){const h=hit(p,e);if(h?.region!==undefined&&h?.region!==null){if(token===selected&&preview.some(m=>m.to===h.region))travel(h.region);else selectRegion(h.region);}}drag=null;};p.canvas.onpointercancel=()=>drag=null;p.canvas.onwheel=e=>{e.preventDefault();p.zoom=Math.max(.6,Math.min(80,p.zoom*(e.deltaY<0?1.15:.87)));schedule();};new ResizeObserver(schedule).observe(p.canvas);return p;}
function views(count){while(panes.length<count)panes.push(createPane(panes.length));while(panes.length>count)panes.pop().el.remove();$('#panes').classList.toggle('multi',count>1);schedule();}$('#views').onchange=e=>views(Number(e.target.value));$('#destination').onchange=schedule;
async function load(){try{const response=await fetch('data/atlas.json');if(!response.ok)throw Error(`Atlas download failed (${response.status})`);data=EarthAtlas.prepare(await response.json());for(const c of data.countries){c.feature=feature(c.geometry);countryById.set(c.id,c);}for(const r of data.regions)r.feature=feature(r.geometry);data.land=data.regions.filter(r=>r.country!==null);data.ocean=data.regions.filter(r=>r.country===null);$('#stats').innerHTML=`<div><strong>${data.countries.length}</strong>countries &amp; territories</div><div><strong>${data.manifest.source_province_features.toLocaleString()}</strong>province features</div><div><strong>${data.cities.length.toLocaleString()}</strong>city names</div><div><strong>${data.ocean.length.toLocaleString()}</strong>ocean spaces</div>`;const atl=data.cities.find(c=>c.name==='Atlanta');jewels=new Set(Array.isArray(saved?.jewels)?saved.jewels:atl?[atl.key]:[]);if(saved&&Number.isFinite(saved.total)&&saved.total>=0){total=saved.total;ledger=Array.isArray(saved.ledger)?saved.ledger.filter(x=>typeof x==='string'):[];if(Number.isInteger(saved.token)&&data.regions[saved.token])token=saved.token;}$('#loading').hidden=true;views(1);if(Number.isInteger(saved?.selected)&&data.regions[saved.selected])selectRegion(saved.selected);window.EarthKingsUI={selectRegion,selectCity:selectCityByName,focusRegion,snapshot:()=>({selected,token,total,ledger:[...ledger],jewels:[...jewels],destinations:preview.map(m=>({...m,path:[...m.path]})),counts:{countries:data.countries.length,regions:data.regions.length,cities:data.cities.length},views:panes.map(p=>({mode:p.mode,lon:p.lon,lat:p.lat,zoom:p.zoom}))}),regionAt:locate,region:id=>data.regions[id],project:(i,coord)=>panes[i].proj(coord)};}catch(e){$('#loading').textContent=`${e.message}. Reload to retry; the original three-player game remains available above.`;}}
function selectCityByName(name){const c=data.cities.find(c=>c.name===name);if(c)selectCity(c);}
load();
})();
