const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),A=require('./atlas-core.js'),d3=require('./vendor/d3-7.9.0.min.js'),data=A.prepare(require('./data/atlas.json'));
assert.equal(data.countries.length,258);assert.equal(data.manifest.source_province_features,4596);assert.equal(data.cities.length,7342);assert.equal(data.regions.filter(r=>r.country===null).length,1778);
const countryMap=new Map(data.countries.map(c=>[c.id,c]));assert.equal(countryMap.size,data.countries.length);
for(const r of data.regions){assert.equal(data.regions[r.id],r);assert.equal(r.routes.length,8);assert.ok(r.name&&r.geometry&&r.extent.length===4);if(r.country)assert.ok(countryMap.has(r.country));for(const n of r.neighbors){assert.ok(data.regions[n].neighbors.includes(r.id));assert.notEqual(n,r.id);}for(let d=0;d<8;d++)for(const n of r.routes[d]){assert.ok(data.regions[n]);assert.notEqual(n,r.id);if(d%2===0)assert.ok(r.neighbors.includes(n));}}
const georgia=data.regions.find(r=>r.name==='Georgia'&&r.country==='USA'),alabama=data.regions.find(r=>r.name==='Alabama'&&r.country==='USA');assert.ok(georgia&&alabama);assert.ok(georgia.neighbors.includes(alabama.id));assert.ok(d3.geoContains(georgia.geometry,[-84.367642,33.739457]));assert.ok(d3.geoContains(alabama.geometry,alabama.center));
const seoul=data.cities.find(c=>c.name==='Seoul');assert.equal(seoul.country,'KOR');assert.ok(data.regions.some(r=>r.country==='KOR'&&d3.geoContains(r.geometry,seoul.center)));
assert.ok(data.countries.every(c=>d3.geoArea(c.geometry)<2*Math.PI));const antarctica=countryMap.get('ATA');assert.ok(d3.geoContains(antarctica.geometry,[0,-85]));assert.ok(!d3.geoContains(antarctica.geometry,[0,0]));
console.log('PASS: source coverage, stable identities, reciprocal border connections, named real provinces/cities, spherical polygon orientation.');
for(const [a,b]of data.polar_links){assert.ok(data.regions[a].neighbors.includes(b));assert.ok(data.regions[b].neighbors.includes(a));const to=A.next(data,a,0);assert.equal(to.to,b);assert.equal(to.d,4);}
assert.equal(data.polar_links.length,15);assert.ok(data.date_line_links.length>0);
for(const type of ['R','B','N','Q','K','P']){const moves=A.routes(data,georgia.id,type);assert.ok(moves.length,type);assert.equal(new Set(moves.map(m=>m.to)).size,moves.length);for(const m of moves){assert.ok(m.path.length&&m.path.at(-1)===m.to);assert.ok(A.journeyDistance(data,georgia.id,m.path)>0);}}
assert.ok(Math.abs(A.distance([0,0],[1,0])-111.1949)<.01);
const reference=require('./data/prototype-reference.json');for(const[name,hash]of Object.entries(reference.files_sha256)){const bytes=fs.readFileSync(path.join(__dirname,'../worlds-of-kings',name));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),hash,name+' original changed');}
console.log('PASS: polar/date-line links, six piece lenses, travel distances, original playable edition preserved byte-for-byte.');
