(()=>{'use strict';
const E=WorldKings,$=s=>document.querySelector(s),symbols={K:'♚',Q:'♛',R:'♜',B:'♝',N:'♞',P:'♟'},stock=['K','Q','R','R','B','B','N','N',...Array(8).fill('P')],pieceNames={K:'King',Q:'Queen',R:'Rook',B:'Bishop',N:'Knight',P:'Pawn'};
let game=E.fresh(),selected=null,moves=[],offer=null,deployment=null,deadline=0,panes=[];game.phase='ready';
function save(){try{localStorage.setItem('worlds-of-kings-v1',JSON.stringify({game,deployment,deadline}));}catch{}}
try{const saved=JSON.parse(localStorage.getItem('worlds-of-kings-v1')||'null');if(saved&&['ready','setup','play','finished'].includes(saved.game?.phase)&&saved.game.players?.length===3&&saved.game.alliances?.length===3&&saved.game.km?.length===3&&saved.game.pieces?.every(p=>Number.isInteger(p.at)&&p.at>=0&&p.at<E.cells.length&&symbols[p.type]&&p.owner>=0&&p.owner<3)&&new Set(saved.game.pieces.map(p=>p.at)).size===saved.game.pieces.length){game=saved.game;deployment=saved.deployment;deadline=saved.deadline;}}catch{}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function remaining(owner){const list=[...stock];game.pieces.filter(p=>p.owner===owner).forEach(p=>{const i=list.indexOf(p.type);if(i>=0)list.splice(i,1);});return list;}
function focus(owner){const c=E.COUNTRIES[owner];panes[0].lon=E.cells[E.id(c.x+1,c.y+1)].lon;panes[0].lat=E.cells[E.id(c.x+1,c.y+1)].lat;drawAll();}
function selection(id){selected=game.pieces.find(p=>p.id===id)||null;moves=selected?E.legal(game,selected):[];$('#accessible-piece').value=selected?String(selected.id):'';$('#accessible-destination').innerHTML=moves.map(m=>`<option value="${m.to}">${esc(E.cells[m.to].name)}${m.capture?' · capture':''}</option>`).join('');$('#accessible-move').disabled=!moves.length;drawAll();if(selected)$('#status').textContent=`${pieceNames[selected.type]} · ${E.cells[selected.at].name}. ${moves.length} legal destinations${selected.type==='P'?' · green advances, coral captures':''}.`;}
function notify(text){$('#status').textContent=text;}
function update(){selected=null;moves=[];$('#setup-panel').hidden=game.phase!=='setup';$('#play-panel').hidden=game.phase!=='play';$('#offer').hidden=!offer;$('#round').textContent=game.phase==='play'?`ROUND ${game.round} · GLOBAL SEQUENTIAL ORDER`:game.phase==='setup'?'TIMED DEPLOYMENT':game.phase==='finished'?'MATCH COMPLETE':'LOCAL HOTSEAT · THREE PLAYERS';
$('#turn').textContent=game.phase==='setup'?`${E.COUNTRIES[deployment].name}, deploy.`:game.phase==='play'?`${game.players[game.turn].name} to move.`:game.phase==='finished'?(game.winner.length>1?'Shared victory.':game.winner.length?'One king remains.':'The ocean is quiet.'):'Meet your world.';
$('#accessible-piece').innerHTML='<option value="">Choose a piece</option>'+game.pieces.filter(p=>p.owner===game.turn).map(p=>`<option value="${p.id}">${pieceNames[p.type]} · ${esc(E.cells[p.at].name)}</option>`).join('');$('#accessible-destination').innerHTML='';$('#accessible-move').disabled=true;
if(game.phase==='play'){$('#status').textContent=E.inCheck(game,game.turn)?'Your king is in check. Finish your move with it safe.':'Select one of your pieces; highlighted spaces are legal destinations.';$('#pass').hidden=E.allLegal(game,game.turn).length>0;}else if(game.phase==='setup'){$('#status').textContent='Choose a piece, then an empty province in your country. Remaining pieces deploy randomly at zero.';}else if(game.phase==='finished'){$('#status').textContent=game.winner.length?game.winner.map(id=>game.players[id].name).join(' + '):'Every army has left the board.';}else $('#status').textContent='Start a quick match or place armies under a 45-second timer.';
$('#players').innerHTML=game.players.map(p=>`<div class="player ${p.alive?'':'out'} ${(game.phase==='play'&&game.turn===p.id)||(game.phase==='setup'&&deployment===p.id)?'active':''}" style="--player:${E.COUNTRIES[p.id].color}"><strong>${esc(p.name)}</strong><span>${p.alive?game.pieces.filter(q=>q.owner===p.id).length+' pieces · alliance '+(game.alliances[p.id]+1):'Eliminated'} · ${p.score===null?'unscored':p.score===.5?'½ point':p.score+' point'+(p.score===1?'':'s')}</span><span>${Math.round(game.km[p.id]).toLocaleString()} km travelled along game routes</span></div>`).join('');
if(game.phase==='setup')$('#piece-choice').innerHTML=[...new Set(remaining(deployment))].map(t=>`<option value="${t}">${symbols[t]} ${pieceNames[t]} (${remaining(deployment).filter(x=>x===t).length} left)</option>`).join('');
$('#rival').innerHTML=game.players.filter(p=>p.alive&&p.id!==game.turn&&!E.allied(game,p.id,game.turn)).map(p=>`<option value="${p.id}">${esc(p.name)} · ${game.requests[`${game.turn}:${p.id}`]||0}/3 sent</option>`).join('');$('#request').disabled=!$('#rival').options.length||!!offer;
$('#log').innerHTML=game.log.slice(-50).reverse().map(x=>`<li>${esc(x)}</li>`).join('');save();drawAll();}
function beginSetup(){if(!confirmReset())return;game=E.fresh();deployment=0;deadline=Date.now()+45000;offer=null;update();focus(0);}
function confirmReset(){return game.phase==='ready'||confirm('Replace the current local match?');}
function finishDeployment(){if(game.phase!=='setup')return;const owner=deployment;E.deploy(game,owner,true);game.log.push(`${E.COUNTRIES[owner].name}: deployment complete.`);deployment++;if(deployment>=3){deployment=null;game.phase='play';game.turn=0;deadline=0;}else deadline=Date.now()+45000;update();focus(deployment??game.turn);}
$('#accessible-piece').onchange=e=>{if(e.target.value!=='')selection(Number(e.target.value));};$('#accessible-move').onclick=()=>{if($('#accessible-destination').value!=='')click(Number($('#accessible-destination').value));};
$('#quick').onclick=()=>{if(!confirmReset())return;game=E.fresh();for(let i=0;i<3;i++)E.deploy(game,i);game.phase='play';game.log.push('Three ready-made armies deploy. The little world opens.');offer=null;deployment=null;deadline=0;update();focus(0);};$('#setup').onclick=beginSetup;$('#finish-setup').onclick=finishDeployment;
$('#reset').onclick=()=>{if(!confirmReset())return;game=E.fresh();game.phase='ready';deployment=null;deadline=0;offer=null;update();};$('#pass').onclick=()=>{try{E.pass(game);offer=null;update();}catch(e){notify(e.message);}};
$('#request').onclick=()=>{try{const b=Number($('#rival').value);offer=E.request(game,game.turn,b);$('#offer-text').textContent=`Pass the device to ${game.players[b].name}. Accepting joins: ${offer.members.map(id=>game.players[id].name).join(', ')}. Request ${offer.count}/3 to this rival.`;$('#diplomacy').textContent='Waiting for the recipient’s decision. No chess move is consumed.';save();$('#offer').hidden=false;$('#request').disabled=true;}catch(e){$('#diplomacy').textContent=e.message;}};
$('#accept').onclick=()=>{if(!offer)return;try{E.accept(game,offer);offer=null;$('#diplomacy').textContent='Complete alliances merged.';update();}catch(e){$('#diplomacy').textContent=e.message;offer=null;update();}};$('#decline').onclick=()=>{if(!offer)return;game.log.push(`${game.players[offer.b].name} declines ${game.players[offer.a].name}’s request.`);offer=null;$('#diplomacy').textContent='Declined. The request remains counted.';update();};
setInterval(()=>{if(game.phase==='setup'&&deployment!==null){const seconds=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('#timer').textContent=`${seconds}s remaining · ${remaining(deployment).length} pieces unplaced`;if(seconds===0)finishDeployment();}},250);
const RX=[1,.9986,.9954,.99,.9822,.973,.96,.9427,.9216,.8962,.8679,.835,.7986,.7597,.7186,.6732,.6213,.5722,.5322],RY=[0,.062,.124,.186,.248,.31,.372,.434,.4958,.5571,.6176,.6769,.7346,.7903,.8435,.8936,.9394,.9761,1];
function robin(lat){const a=Math.abs(lat)/5,i=Math.min(17,Math.floor(a)),t=Math.min(1,a-i);return[RX[i]*(1-t)+RX[i+1]*t,(lat<0?-1:1)*(RY[i]*(1-t)+RY[i+1]*t)];}
function project(p,lon,lat,w,h){const rad=Math.PI/180,dl=(((lon-p.lon+540)%360)-180)*rad,b=lat*rad,b0=p.lat*rad;if(p.mode==='globe'){const depth=Math.sin(b0)*Math.sin(b)+Math.cos(b0)*Math.cos(b)*Math.cos(dl),r=Math.min(w,h)*.43*p.zoom;return{x:w/2+r*Math.cos(b)*Math.sin(dl),y:h/2-r*(Math.cos(b0)*Math.sin(b)-Math.sin(b0)*Math.cos(b)*Math.cos(dl)),depth};}if(p.mode==='mercator'){const cap=Math.max(-85,Math.min(85,lat)),v=Math.log(Math.tan(Math.PI/4+cap*rad/2));return{x:w/2+dl/(2*Math.PI)*w*.94*p.zoom,y:h/2-v/(2*Math.PI)*w*.94*p.zoom,depth:1};}const[x,y]=robin(lat);return{x:w/2+dl/Math.PI*x*w*.46*p.zoom,y:h/2-y*h*.43*p.zoom,depth:1};}
function landVertex(x,y){const xx=((x%E.W)+E.W)%E.W,land=[E.id(xx,Math.max(0,Math.min(E.H-1,y))),E.id(xx-1,Math.max(0,Math.min(E.H-1,y))),E.id(xx,Math.max(0,Math.min(E.H-1,y-1))),E.id(xx-1,Math.max(0,Math.min(E.H-1,y-1)))].some(n=>E.cells[n].country!==null);if(!land||y===0||y===E.H)return[x*360/E.W-180,90-y*180/E.H];const jitter=(Math.sin(xx*19.4+y*7.3)*.5+Math.sin(xx*5+y*17)*.5);return[(x+jitter*.15)*360/E.W-180,90-(y+Math.cos(xx*8+y*11)*.13)*180/E.H];}
function path(ctx,points){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();}
function route(ctx,p,ids,w,h,color,dashed=false){const points=ids.map(n=>project(p,E.cells[n].lon,E.cells[n].lat,w,h));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash(dashed?[4,4]:[]);ctx.beginPath();let prev=null;for(const q of points){if(q.depth<=.02){prev=null;continue;}if(prev&&Math.abs(q.x-prev.x)<w*.55)ctx.lineTo(q.x,q.y);else ctx.moveTo(q.x,q.y);prev=q;}ctx.stroke();ctx.setLineDash([]);}
function draw(p){const canvas=p.canvas,ctx=canvas.getContext('2d'),w=canvas.clientWidth||700,h=canvas.clientHeight||500,dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.scale(dpr,dpr);ctx.fillStyle='#102c43';ctx.fillRect(0,0,w,h);p.hit=[];const r=Math.min(w,h)*.43*p.zoom;
if(p.mode==='globe'){ctx.save();ctx.beginPath();ctx.arc(w/2,h/2,r,0,Math.PI*2);ctx.clip();ctx.fillStyle='#204b68';ctx.fillRect(0,0,w,h);}else if(p.mode==='mercator'){ctx.fillStyle='#bddeea';ctx.font='10px system-ui';ctx.fillText('Mercator · polar extent clipped at 85° · globe shows crossing routes',12,h-12);}
const data=E.cells.map(c=>({c,q:project(p,c.lon,c.lat,w,h)})).filter(x=>x.q.depth>.015).sort((a,b)=>a.q.depth-b.q.depth);
for(const{c,q}of data){const corners=[[c.x,c.y],[c.x+1,c.y],[c.x+1,c.y+1],[c.x,c.y+1]].map(([x,y])=>{const[lon,lat]=landVertex(x,y);return project(p,lon,lat,w,h);});if(p.mode!=='globe'&&Math.max(...corners.map(v=>v.x))-Math.min(...corners.map(v=>v.x))>w*.55)continue;path(ctx,corners);ctx.fillStyle=c.country===null?((c.x+c.y)%2?'#234d68':'#2d5b75'):E.COUNTRIES[c.country].color;ctx.fill();ctx.strokeStyle=c.country===null?'#769eb349':'#182f4160';ctx.lineWidth=c.country===null?.65:1.1;ctx.stroke();p.hit.push({id:c.id,points:corners,center:q});if(game.phase==='setup'&&c.country===deployment&&!E.occupant(game,c.id)){path(ctx,corners);ctx.fillStyle='#fff7ce45';ctx.fill();}
if(c.country===null&&(c.y===1||c.y===E.H-2)&&c.x%6===0){ctx.fillStyle='#abc5d8';ctx.font=`${Math.max(8,w/95)}px system-ui`;ctx.textAlign='center';ctx.fillText('⋔',q.x,q.y+3);}}
for(const m of moves){route(ctx,p,[selected.at,...m.path],w,h,m.capture?'#ffad98':'#b3ffde',selected.type==='N');const c=E.cells[m.to],q=project(p,c.lon,c.lat,w,h);if(q.depth>.02){ctx.beginPath();ctx.arc(q.x,q.y,Math.max(3,w/140),0,Math.PI*2);ctx.fillStyle=m.capture?'#ff9786':'#98eddf';ctx.fill();}}
if(selected){const c=E.cells[selected.at],q=project(p,c.lon,c.lat,w,h);if(q.depth>0){ctx.beginPath();ctx.arc(q.x,q.y,Math.max(9,w/55),0,Math.PI*2);ctx.strokeStyle='#fff6cc';ctx.lineWidth=2.5;ctx.stroke();}}
for(const piece of game.pieces){const c=E.cells[piece.at],q=project(p,c.lon,c.lat,w,h);if(q.depth<.06)continue;const size=Math.max(11,Math.min(29,w/35))*p.zoom*(p.mode==='globe'?.7+.3*q.depth:1);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${size}px "DejaVu Sans",serif`;ctx.strokeStyle='#122f43';ctx.lineWidth=3;ctx.strokeText(symbols[piece.type],q.x,q.y);ctx.fillStyle=E.COUNTRIES[piece.owner].color;ctx.fillText(symbols[piece.type],q.x,q.y);}
if(p.labels){ctx.textAlign='center';ctx.textBaseline='alphabetic';for(const country of E.COUNTRIES){const c=E.cells[E.id(country.x+1,country.y+1)],q=project(p,c.lon,c.lat,w,h);if(q.depth>.12){ctx.font=`600 ${Math.max(9,Math.min(13,w/60))}px system-ui`;ctx.strokeStyle='#102c43';ctx.lineWidth=4;ctx.strokeText(country.name,q.x,q.y-25);ctx.fillStyle='#fff4d8';ctx.fillText(country.name,q.x,q.y-25);}}ctx.font='9px system-ui';ctx.fillStyle='#abc9d6';for(let y=2;y<E.H;y+=3){const q=project(p,p.lon-65,90-y*180/E.H,w,h);if(q.depth>.2)ctx.fillText(`${Math.abs(Math.round(90-y*180/E.H))}°${90-y*180/E.H>=0?'N':'S'}`,q.x,q.y);}for(let x=0;x<E.W;x+=4){const lon=x*360/E.W-180,q=project(p,lon,0,w,h);if(q.depth>.2)ctx.fillText(`${Math.abs(lon)}°${lon<0?'W':'E'}`,q.x,q.y+8);}}
if(p.mode==='globe'){ctx.restore();ctx.beginPath();ctx.arc(w/2,h/2,r,0,Math.PI*2);ctx.strokeStyle='#78a7bf';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#a9cbd6';ctx.font='10px system-ui';ctx.textAlign='left';ctx.fillText('Drag to rotate · scroll to zoom · click a province or piece',12,h-12);}}
function contains(x,y,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if((a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;}
function hit(p,event){const rect=p.canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;return[...p.hit].reverse().find(v=>contains(x,y,v.points))?.id;}
function click(n){if(n===undefined)return;if(offer){notify('Let the alliance recipient accept or decline before continuing.');return;}if(game.phase==='setup'){if(E.cells[n].country!==deployment||E.occupant(game,n)){notify('Choose an empty province in the deploying country.');return;}const type=$('#piece-choice').value;if(!remaining(deployment).includes(type))return;E.addPiece(game,deployment,type,n);if(!remaining(deployment).length)finishDeployment();else update();return;}if(game.phase!=='play'){notify('Start a match to move pieces.');return;}const target=moves.find(m=>m.to===n);if(selected&&target){try{E.move(game,selected.id,n,$('#promotion').value);update();}catch(e){notify(e.message);}return;}const p=E.occupant(game,n);if(p&&p.owner===game.turn)selection(p.id);else{selected=null;moves=[];drawAll();notify(p?`That piece belongs to ${game.players[p.owner].name}.`:'Select one of the current country’s pieces.');}}
function createPane(i){const el=document.createElement('section');el.className='pane';el.setAttribute('aria-label',`Map view ${i+1}`);el.innerHTML=`<div class="pane-tools"><span class="pane-title">VIEW ${i+1}</span><select aria-label="Projection for view ${i+1}"><option value="globe">3D globe</option><option value="mercator">Mercator</option><option value="robinson">Robinson</option></select><button data-action="home" title="Focus current country">Home</button><button data-action="north" title="North Pole">N↑</button><button data-action="south" title="South Pole">S↓</button><button data-action="opposite" title="Opposite side">↔</button><button data-action="labels" aria-pressed="true">Names</button><button data-action="zoom-in" aria-label="Zoom in">+</button><button data-action="zoom-out" aria-label="Zoom out">−</button></div><canvas tabindex="0" role="img" aria-label="Interactive fictional geography board. Select pieces with the mouse or touch; legal moves are highlighted."></canvas>`;$('#panes').append(el);const p={el,canvas:el.querySelector('canvas'),mode:'globe',lon:i===1?60:-120,lat:i===2?90:i===3?-90:-20,zoom:1,labels:true,hit:[]};el.querySelector('select').onchange=e=>{p.mode=e.target.value;if(p.mode!=='globe')p.lon=0;p.zoom=1;draw(p);};for(const b of el.querySelectorAll('button'))b.onclick=()=>{const action=b.dataset.action;if(action==='home'){const c=E.COUNTRIES[deployment??game.turn],v=E.cells[E.id(c.x+1,c.y+1)];p.lon=v.lon;p.lat=v.lat;}if(action==='north'){p.lat=90;p.mode='globe';el.querySelector('select').value='globe';}if(action==='south'){p.lat=-90;p.mode='globe';el.querySelector('select').value='globe';}if(action==='opposite'){p.lon+=180;p.lat=-p.lat;}if(action==='labels'){p.labels=!p.labels;b.setAttribute('aria-pressed',String(p.labels));}if(action==='zoom-in')p.zoom=Math.min(2.5,p.zoom*1.2);if(action==='zoom-out')p.zoom=Math.max(.6,p.zoom/1.2);draw(p);};
let drag=null;p.canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};p.canvas.setPointerCapture(e.pointerId);};p.canvas.onpointermove=e=>{if(drag){if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5)drag.moved=true;if(drag.moved){p.lon-=(e.clientX-drag.x)*.4;if(p.mode==='globe')p.lat=Math.max(-90,Math.min(90,p.lat+(e.clientY-drag.y)*.4));p.canvas.classList.add('dragging');draw(p);}drag.x=e.clientX;drag.y=e.clientY;}const n=hit(p,e);if(n!==undefined){const c=E.cells[n];$('#hover').textContent=`${c.name} · ${Math.abs(c.lat).toFixed(1)}°${c.lat>=0?'N':'S'}, ${Math.abs(c.lon).toFixed(1)}°${c.lon>=0?'E':'W'}${c.country===null&&(c.y===1||c.y===E.H-2)&&c.x%6===0?' · three-way pawn advance junction':''}`;}};p.canvas.onpointerup=e=>{if(drag&&!drag.moved)click(hit(p,e));drag=null;p.canvas.classList.remove('dragging');};p.canvas.onpointercancel=()=>{drag=null;p.canvas.classList.remove('dragging');};p.canvas.onwheel=e=>{e.preventDefault();p.zoom=Math.max(.6,Math.min(2.5,p.zoom*(e.deltaY<0?1.1:.9)));draw(p);};new ResizeObserver(()=>draw(p)).observe(p.canvas);return p;}
function drawAll(){panes.forEach(draw);}function setViews(count){while(panes.length<count)panes.push(createPane(panes.length));while(panes.length>count)panes.pop().el.remove();$('#panes').classList.toggle('multi',count>1);requestAnimationFrame(drawAll);}$('#views').onchange=e=>setViews(Number(e.target.value));setViews(1);update();if(game.phase==='setup')focus(deployment);else if(game.phase==='play')focus(game.turn);
// The exported snapshot is a local development aid, never an online authority grant.
window.WorldKingsUI={snapshot:()=>JSON.parse(JSON.stringify(game)),selectPiece:selection,clickSpace:click,projection:project};
WorldPlaceNavigation.mount(document.getElementById('place-navigation'),place=>{const p=panes[0];if(!p)return;p.lon=place.center[0];p.lat=place.center[1];p.mode='globe';p.el.querySelector('select').value='globe';p.zoom=Math.min(2.5,place.zoom);document.getElementById('hover').textContent=place.name+' · viewing reference; fictional board unchanged.';drawAll();},true);
})();
