(()=>{'use strict';const $=id=>document.getElementById(id),fields=['care','retreat','enrichment','attractants','exposure'];let night=false;
function render(){const o={protected:$('scenario').value==='refuge',bears:Number($('bears').value)};for(const k of fields){o[k]=Number($(k).value)/100;$(k+'-value').value=o[k].toFixed(2);}const result=LionLamb.simulate(o),last=result.rows.at(-1);for(const k of['welfare','stress','encounter'])$(k).textContent=last[k].toFixed(2);$('scenario-note').textContent=o.protected?'Buffer residents keep their natural weapons. Trained friendliness, protected contact, supervision, and retreat are separate story safeguards.':'Shared contact is a speculative scenario. The toy model does not make training a guarantee or erase contact pressure.';$('scene-mode').textContent=o.protected?'ZONE 2 · THE MANAGED BUFFER':'ZONE 2 · SHARED-SPACE THOUGHT EXPERIMENT';drawAnimal($('species').value);$('bear-b').setAttribute('opacity',o.bears===2?'1':'0');$('habitat').style.background=night?'#dae0e8':'';$('habitat').style.filter=night?'brightness(.88) saturate(.85)':'none';$('day').setAttribute('aria-pressed',String(!night));$('night').setAttribute('aria-pressed',String(night));const colors={welfare:'#477c51',stress:'#b76a4a',habituation:'#6a77a0',foodAssociation:'#ad902f'};let svg='';for(const y of[0,.25,.5,.75,1])svg+=`<path d="M48 ${240-y*210}H875" stroke="#e3e7dd"/><text x="12" y="${244-y*210}" font-size="12" fill="#607165">${y}</text>`;for(const[key,color]of Object.entries(colors)){const path=result.rows.map((r,i)=>`${i?'L':'M'}${48+r.day/60*827},${240-r[key]*210}`).join(' ');svg+=`<path d="${path}" fill="none" stroke="${color}" stroke-width="3"/>`;}svg+='<text x="48" y="267" font-size="12" fill="#607165">Day 0</text><text x="825" y="267" font-size="12" fill="#607165">Day 60</text>';$('chart').innerHTML=svg;$('chart').setAttribute('aria-label',`Synthetic day-60 indices: welfare ${last.welfare.toFixed(2)}, stress ${last.stress.toFixed(2)}, habituation ${last.habituation.toFixed(2)}, food association ${last.foodAssociation.toFixed(2)}. Not calibrated predictions.`);window.LionLambUI={result:()=>result};}
function drawAnimal(species){
 if(species==='lion'||species==='tiger'){$('bear-a').innerHTML=`<text x="-45" y="22" style="font-size:78px;letter-spacing:0">${species==='lion'?'🦁':'🐅'}</text>`;}
 const color=species==='bear'?'#725947':species==='raccoon'?'#7b827a':'#a0a49b';
 const tail=species==='raccoon'?'<path d="M-35 5Q-100 5 -75 35" stroke="#7b827a" stroke-width="18" fill="none"/><path d="M-53 7l-3 16M-76 12l-8 9" stroke="#353e35" stroke-width="8"/>':species==='opossum'?'<path d="M-35 5Q-110 30 -80 48" stroke="#cbacaa" stroke-width="6" fill="none"/>':'';
 const head=species==='opossum'?'<path d="M25 -24L65 0L25 20Z" fill="#f6f2e7"/><circle cx="25" cy="-25" r="9" fill="#565c55"/><circle cx="61" cy="0" r="4" fill="#c59c9a"/>':`<circle cx="35" cy="-8" r="22" fill="${color}"/><circle cx="25" cy="-27" r="9" fill="${color}"/><circle cx="47" cy="-26" r="9" fill="${color}"/>${species==='raccoon'?'<path d="M20 -12Q35 -25 53 -12L50 -3H22Z" fill="#323d33"/>':''}<ellipse cx="48" cy="0" rx="12" ry="8" fill="#ded7c8"/>`;
 if(!['lion','tiger'].includes(species))$('bear-a').innerHTML=`${tail}<ellipse rx="43" ry="27" fill="${color}"/>${head}<circle cx="43" cy="-10" r="3" fill="#202820"/><path d="M-25 19v17M5 21v15M30 15v21" stroke="${color}" stroke-width="12" stroke-linecap="round"/>`;
 const names={lion:'Lion',tiger:'Tiger',bear:'Bear',raccoon:'Raccoon',opossum:'Opossum'},name=names[species];$('story-title').textContent=night?`${name} beneath the evening stars.`:`${name} at the garden gate.`;const stories={lion:'The lion lies beside the creek, mane bright in the afternoon sun. The children watch from the hearth. Somewhere beyond the garden, a branch breaks. He lifts his head—not because every stranger is an enemy, but because this is the place he has chosen to protect.',tiger:'The tiger keeps a quiet path between the trees and the pond. She can vanish into shade whenever she likes. At the border, her striped presence asks the deep wild to pause. At home, she has room for play, a generous table, and no need to perform.',bear:'The bear takes the long way to the pond. He has his own patch of shade, his own afternoon, and a household that has learned to leave him room. When the evening watch begins, his companion may join him—or choose the other garden.',raccoon:'The raccoon makes a tiny kingdom of the creek bank. Clever paws, a mask, and more curiosity than solemnity. He belongs to the border in his own way: noticing everything, disappearing whenever the day asks too much.',opossum:'The opossum arrives as the garden softens into dusk. She is not interested in grandeur. A safe corner, a quiet path, and the freedom to be unremarkable are enough. In this kingdom, even the smallest guardian gets a chapter.'};$('story-text').textContent=stories[species]+' Here in Zone 2, natural teeth and claws remain. Training encourages friendliness in the story; protected human areas, separate prey refuges, supervision, and retreat remain necessary layers.'+(night?' Lanterns kindle at the human edge. The guardians hold the outer watch; each can return to a private retreat.':' Beyond this managed buffer lies the wild-wild, with minimal human intervention.');$('scene-title').textContent=`${name} in a fictional guardian landscape`;
}
$('species').onchange=render;for(const k of fields)$(k).oninput=render;$('bears').onchange=render;$('scenario').onchange=()=>{const refuge=$('scenario').value==='refuge';$('exposure').value=refuge?20:75;$('attractants').value=refuge?10:70;render();};$('day').onclick=()=>{night=false;render();};$('night').onclick=()=>{night=true;render();};$('reset').onclick=()=>{$('scenario').value='refuge';$('species').value='lion';$('bears').value='1';for(const k of fields)$(k).value={care:80,retreat:80,enrichment:80,attractants:10,exposure:20}[k];night=false;render();};render();})();
