'use strict';
const $=id=>document.getElementById(id);let result;
function node(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function compile(){result=ECC.compile($('premises').value);$('steps').replaceChildren();$('issues').replaceChildren();$('status').textContent=`${result.rules.length} rules · ${result.steps.length} facts and conclusions · ${result.conflicts.length} conflicts · ${result.rejected.length} unsupported lines`;
for(const f of result.steps){const li=node('li',`${f.subject} is ${f.negative?'not ':''}${f.predicate}`);li.append(node('small',`${f.reason}; line ${f.line}${f.premises.length?`; from step ${f.premises.join(', ')}`:''}.`));$('steps').append(li);}
for(const r of result.rejected)$('issues').append(node('p',`Excluded line ${r.line}: ${r.source}. ${r.reason}`));for(const pair of result.conflicts)$('issues').append(node('p',`Conflict: steps ${pair.join(' and ')} assert opposite claims. Neither is silently discarded.`));ask();}
function ask(){if(!result)return;const q=ECC.query(result,$('question').value);const labels={supported:'Supported by the premises',opposed:'Its negation is supported',both:'Both the claim and its negation are supported: conflict',unresolved:'Unresolved: neither the claim nor its negation is derived',unsupported:'Unsupported query: use “NAME is TERM” or “NAME is not TERM”'};$('answer').textContent=labels[q.status]+(q.yes?` · step ${q.yes}`:'')+(q.no?` · opposing step ${q.no}`:'')+(result.rejected.length?' · based only on accepted lines':'');}
$('compile').onclick=compile;$('ask').onclick=()=>{compile();};$('conflict-example').onclick=()=>{$('premises').value='Every bachelor is unmarried\nEvery unmarried is not married\nManny is bachelor\nManny is married';compile();};$('reset-example').onclick=()=>{$('premises').value='Every bachelor is unmarried\nEvery unmarried is not married\nManny is bachelor';compile();};$('export-proof').onclick=()=>{compile();download('ecc-proof.json',{input:$('premises').value,query:$('question').value,...result});};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.tab').forEach(s=>s.hidden=s.id!==b.dataset.tab);});
const glossary={papa:[['father','baba'],['affectionate address','baba (context-dependent)']],man:[['adult male person','adam']],one:[['number 1','bir']],two:[['number 2','iki']],three:[['number 3','üç']],good:[['of satisfactory quality','iyi'],['morally commendable','iyi (context-dependent)']]};function meanings(){$('meanings').replaceChildren();for(const [sense,tr] of glossary[$('word').value]){const card=node('article','');card.append(node('h3',sense),node('p',`${$('word').value} ↔ ${tr}`));$('meanings').append(card);}}$('word').onchange=meanings;
let records=[];let storageWorks=true;try{const data=JSON.parse(localStorage.getItem('ecc-records')||'[]');if(Array.isArray(data))records=data.filter(r=>r&&typeof r.text==='string'&&typeof r.source==='string');}catch{storageWorks=false;}
function showRecords(){$('records').replaceChildren();if(!records.length)$('records').append(node('p','No records yet. Add your first expression.'));for(const r of records){const card=node('article','');card.append(node('blockquote',r.text),node('small',r.source||'Source not specified'));if(r.interpretation)card.append(node('p',`Interpretation: ${r.interpretation}`));$('records').append(card);}}
$('save-record').onclick=()=>{const text=$('expression').value.trim();if(!text){$('record-status').textContent='Add an expression first.';return;}records.push({text,source:$('source').value.trim(),interpretation:$('interpretation').value.trim(),recorded:new Date().toISOString()});try{localStorage.setItem('ecc-records',JSON.stringify(records));storageWorks=true;}catch{storageWorks=false;}$('record-status').textContent=storageWorks?'Saved on this device.':'Kept for this session only; storage is unavailable. Export to preserve it.';$('expression').value='';$('interpretation').value='';showRecords();};$('export-records').onclick=()=>download('ecc-records.json',records);compile();meanings();showRecords();
