'use strict';
const $=id=>document.getElementById(id),fmt=x=>(x*100).toFixed(2)+'%';
function draw(){const n=+$('index').value,a=+$('angle').value,out=$('direction').value==='out';const n1=out?n:1,n2=out?1:n;const r=Optics.fresnel(n1,n2,a);$('index-value').textContent=n.toFixed(2);$('angle-value').textContent=a.toFixed(1)+'°';$('power').textContent=fmt(r.r)+' reflected · '+fmt(r.t)+' transmitted';$('polarization').textContent=`s polarization: ${fmt(r.rs)} · p polarization: ${fmt(r.rp)}`;$('explanation').textContent=r.tir?'Total internal reflection: all incident power is reflected in this ideal, lossless case.':`Transmitted ray: ${r.angle.toFixed(1)}° from the normal. ${Math.abs(r.rp)<1e-8&&n1!==n2?'At Brewster’s angle the p-polarized reflection vanishes.':''}`;
const rad=a*Math.PI/180,x=250,y=200,l=170,ix=x-l*Math.sin(rad),iy=y-l*Math.cos(rad),rx=x+l*Math.sin(rad);let s=`<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="context-stroke"/></marker></defs><rect x="0" y="200" width="500" height="230" fill="#1b3f53"/><line x1="15" y1="200" x2="485" y2="200" stroke="#9ebacc"/><line x1="250" y1="15" x2="250" y2="410" stroke="#92a3b6" stroke-dasharray="5 5"/><text x="15" y="30">Incoming medium n = ${n1.toFixed(2)}</text><text x="15" y="410">Second medium n = ${n2.toFixed(2)}</text><line x1="${ix}" y1="${iy}" x2="${x}" y2="${y}" stroke="#ffdc87" stroke-width="4" marker-end="url(#arrow)"/><text x="20" y="75">Incoming ↘</text>`;
if(r.r>1e-10)s+=`<line x1="${x}" y1="${y}" x2="${rx}" y2="${iy}" stroke="#c3b6ff" stroke-width="4" marker-end="url(#arrow)"/><text x="340" y="75">Reflected ↗</text>`;
if(!r.tir){const rt=r.angle*Math.PI/180;s+=`<line x1="${x}" y1="${y}" x2="${x+l*Math.sin(rt)}" y2="${y+l*Math.cos(rt)}" stroke="#94e3c0" stroke-width="4" marker-end="url(#arrow)"/><text x="20" y="300">Transmitted ↘</text>`;}else s+='<text x="25" y="300">No propagating transmitted ray</text>';$('rays').innerHTML=s;}
function metal(){const n=+$('metal-n').value,k=+$('metal-k').value;$('metal-n-value').textContent=n.toFixed(1);$('metal-k-value').textContent=k.toFixed(1);$('metal-power').textContent=fmt(Optics.absorbing(n,k))+' reflected at normal incidence';}
for(const id of ['direction','index','angle'])$(id).addEventListener('input',draw);for(const id of ['metal-n','metal-k'])$(id).addEventListener('input',metal);
$('normal').onclick=()=>{$('angle').value=0;draw();};$('brewster').onclick=()=>{const n=+$('index').value;$('angle').value=(Math.atan($('direction').value==='out'?1/n:n)*180/Math.PI).toFixed(1);draw();};$('internal').onclick=()=>{$('direction').value='out';$('index').value=1.5;$('angle').value=50;draw();};
$('load-video').onclick=()=>{const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/-cAQzSl41G0';frame.title='DemystifySci: How Mirrors Actually Work, Atom by Atom';frame.allow='encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;const box=$('video');box.replaceChildren(frame);const p=document.createElement('p');const a=document.createElement('a');a.href='https://www.youtube.com/watch?v=-cAQzSl41G0';a.textContent='Player unavailable? Open on YouTube ↗';p.append(a);box.append(p);};draw();metal();

function starGarden(){const depth=+$('depth').value;$('depth-value').textContent=depth;let parts=[],count=0;function star(x,y,r,d){count++;const points=Array.from({length:6},(_,i)=>[x+r*Math.cos(i*Math.PI/3-Math.PI/2),y+r*Math.sin(i*Math.PI/3-Math.PI/2)]);for(const order of [[0,2,4],[1,3,5]])parts.push(`<polygon points="${order.map(i=>points[i].join(',')).join(' ')}" fill="none" stroke="${d%2?'#c3b6ff':'#75dce8'}" stroke-width="${d?1:2}" opacity=".8"/>`);if(d<depth)for(const [px,py] of points)star(px,py,r*.28,d+1);}star(250,250,150,0);$('hyperstar-map').innerHTML=parts.join('');$('star-count').textContent=`${count} visible stars · finite preview of an unbounded rule. Each child is 28% of its parent’s radius.`;}
$('depth').addEventListener('input',starGarden);starGarden();
