(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TinyWorld=factory();})(globalThis,function(){
'use strict';
const source={nps:'https://www.nps.gov/grsm/learn/nature/mammal-checklist.htm',fox:'https://animaldiversity.org/accounts/Vulpes_vulpes/',raccoon:'https://onlinelibrary.wiley.com/doi/full/10.1111/mam.12249',koala:'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0162207',uk:'https://www.woodlandtrust.org.uk/trees-woods-and-wildlife/animals/mammals/',nz:'https://www.doc.govt.nz/kiwi',kaka:'https://www.doc.govt.nz/kaka',penguin:'https://www.bas.ac.uk/about/education-and-schools/antarctic-wildlife/',panda:'https://m.panda.org.cn/en/about/',jaguar:'https://www.fws.gov/species/jaguar-panthera-onca',elephant:'https://www.worldwildlife.org/species/elephant/',tiger:'https://www.worldwildlife.org/species/tiger/',orangutan:'https://www.worldwildlife.org/species/orangutan/',marine:'https://www.fisheries.noaa.gov/species/killer-whale',kangaroo:'https://www.dcceew.gov.au/environment/wildlife-trade/natives',waterdeer:'https://www.nie.re.kr/nie/pgm/nature/view.do?contIdx=4&menuNo=200038'};
const catalog=[
 {key:'raccoon',emoji:'🦝',label:'Raccoon',countries:['USA','CAN','MEX','GTM','BLZ','HND','SLV','NIC','CRI','PAN'],box:[-135,5,-65,55],when:'night',source:source.raccoon},
 {key:'bear',emoji:'🐻',label:'American black bear',countries:['USA','CAN'],box:[-170,25,-52,68],source:source.nps},
 {key:'deer',emoji:'🦌',label:'White-tailed deer',countries:['USA','CAN','MEX'],box:[-130,15,-52,60],source:source.nps},
 {key:'fox',emoji:'🦊',label:'Red fox',countries:['GBR','IRL','FRA','DEU','ESP','PRT','ITA','CHE','AUT','BEL','NLD','LUX','POL','CZE','SVK','HUN','ROU','BGR','GRC','ALB','HRV','BIH','SRB','SVN','UKR','BLR','RUS','NOR','SWE','FIN','EST','LVA','LTU','DNK','TUR'],box:[-12,30,180,72],source:source.fox},
 {key:'badger',emoji:'🦡',label:'European badger',countries:['GBR','FRA','DEU','IRL'],box:[-12,35,20,60],when:'night',source:source.uk},
 {key:'hedgehog',emoji:'🦔',label:'Western European hedgehog',countries:['GBR','FRA','DEU','IRL'],box:[-12,35,20,60],when:'night',source:'https://www.woodlandtrust.org.uk/trees-woods-and-wildlife/animals/mammals/hedgehog/'},
 {key:'roe',emoji:'🦌',label:'Roe deer',countries:['GBR','FRA','DEU'],box:[-12,35,20,60],source:source.uk},
 {key:'waterdeer',emoji:'🦌',label:'Korean water deer',note:'Deer emoji has antlers; water deer do not.',countries:['KOR'],box:[125,34,130,39],source:source.waterdeer},
 {key:'koala',emoji:'🐨',label:'Koala',countries:['AUS'],box:[141,-39,154,-17],habitats:['woodland','temperate','tropical'],source:source.koala},
 {key:'kangaroo',emoji:'🦘',label:'Mainland kangaroo group',countries:['AUS'],box:[112,-39,154,-10],source:source.kangaroo,group:true},
 {key:'kiwi',emoji:'🐦',label:'Kiwi',note:'Generic bird emoji stands in for a kiwi.',countries:['NZL'],box:[165,-48,179,-34],when:'night',source:source.nz},
 {key:'kaka',emoji:'🦜',label:'Kākā',countries:['NZL'],box:[165,-48,179,-34],when:'day',source:source.kaka},
 {key:'penguin',emoji:'🐧',label:'Southern coastal penguin group',countries:['ATA','NZL','AUS','ATF','FLK','CHL','ARG','ZAF','NAM'],box:[-180,-90,180,-30],coast:true,source:source.penguin,group:true},
 {key:'seal',emoji:'🦭',label:'Southern seal group',countries:['ATA','NZL','ATF','AUS','FLK','CHL','ARG'],box:[-180,-90,180,-34],coast:true,source:source.penguin,group:true},
 {key:'panda',emoji:'🐼',label:'Giant panda',countries:['CHN'],box:[102,28,109,35],source:source.panda},
 {key:'jaguar',emoji:'🐆',label:'Jaguar',note:'Leopard emoji stands in for a jaguar.',countries:['MEX','GTM','BLZ','HND','NIC','CRI','PAN','COL','VEN','GUY','SUR','FRA','ECU','PER','BOL','BRA','PRY','ARG'],box:[-110,-29,-34,25],source:source.jaguar},
 {key:'elephant',emoji:'🐘',label:'African elephant group',countries:['AGO','BWA','NAM','ZMB','ZWE','KEN','TZA','UGA','ZAF','MOZ','GAB','CMR','COG','COD'],box:[8,-34,43,12],habitats:['savanna','tropical','woodland'],source:source.elephant,group:true},
 {key:'tiger-india',emoji:'🐅',label:'Tiger',countries:['IND','NPL','BGD','BTN'],box:[76,8,95,29],habitats:['tropical','woodland','temperate'],source:source.tiger},
 {key:'tiger-russia',emoji:'🐅',label:'Amur tiger',countries:['RUS','CHN'],box:[130,42,140,51],source:source.tiger},
 {key:'orangutan',emoji:'🦧',label:'Orangutan group',countries:['IDN','MYS'],boxes:[[95,-6,106,6],[108,-5,119,8]],source:source.orangutan,group:true},
 {key:'songbird',emoji:'🐦',label:'Local bird group',box:[-180,-60,180,75],when:'day',group:true,generic:true},
 {key:'butterfly',emoji:'🦋',label:'Regional butterfly group',box:[-180,-50,180,60],when:'day',habitats:['tropical','temperate','woodland','savanna'],group:true,generic:true},
 {key:'bat',emoji:'🦇',label:'Regional bat group',box:[-180,-50,180,60],when:'night',habitats:['tropical','temperate','woodland','savanna'],group:true,generic:true},
 {key:'seabird',emoji:'🐦',label:'Coastal seabird group',coast:true,group:true,generic:true},
 {key:'fish',emoji:'🐟',label:'Marine fish group',marine:true,group:true,generic:true},
 {key:'whale',emoji:'🐋',label:'Ocean whale group',marine:true,group:true,generic:true},
 {key:'orca',emoji:'🐳',label:'Orca',note:'Whale emoji stands in for an orca.',marine:true,source:source.marine},
 {key:'sea-turtle',emoji:'🐢',label:'Sea turtle group',marine:true,box:[-180,-40,180,40],group:true,generic:true}
];
const habitats={temperate:{name:'Temperate garden',color:'#cbdcab',sky:'#dcefe9',items:['leaf','wood','stone'],scene:'🌳 🍃 🌼'},tropical:{name:'Tropical canopy',color:'#99c8aa',sky:'#cfede8',items:['leaf','wood','stone'],scene:'🌴 🌿 🌺'},savanna:{name:'Savanna sketch',color:'#d8d396',sky:'#eeefd7',items:['leaf','wood','stone'],scene:'🌾 🌳 ☀️'},dry:{name:'Dryland sketch',color:'#e2cba8',sky:'#f6e5ce',items:['stone','stone','wood'],scene:'🪨 🌾 ☀️'},woodland:{name:'Woodland sketch',color:'#b7ccac',sky:'#dce8e9',items:['leaf','wood','stone'],scene:'🌲 🍄 🍃'},polar:{name:'Polar coast & ice',color:'#e7edf0',sky:'#dce9f0',items:['stone','shell','stone'],scene:'❄️ 🪨 🌊'},coast:{name:'Island & coastal garden',color:'#c8dfc7',sky:'#daeeee',items:['shell','wood','stone'],scene:'🌊 🐚 🌿'},ocean:{name:'Ocean cove',color:'#abd4df',sky:'#ddedf1',items:['shell','stone','shell'],scene:'🌊 🐚 🪸'}};
function hash(text){let h=2166136261;for(const ch of String(text)){h^=ch.codePointAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function inBox(p,b){return p[0]>=b[0]&&p[0]<=b[2]&&p[1]>=b[1]&&p[1]<=b[3];}
function habitat(r){const [lon,lat]=r.anchor||r.center;if(r.marine)return'ocean';if(r.country==='ATA'||Math.abs(lat)>=66||(lat<-48&&r.shore))return'polar';if(r.country==='AUS'){if(lon>=141)return lat<-23?'temperate':'tropical';return'dry';}if(r.continent==='Africa'&&lat>=14&&lat<=31&&lon<40||['SAU','OMN','ARE','YEM','QAT','KWT'].includes(r.country))return'dry';if(r.continent==='Africa'&&Math.abs(lat)<24)return Math.abs(lat)<7?'tropical':'savanna';if(Math.abs(lat)<23)return'tropical';if(lat>52)return'woodland';if(r.shore&&Math.abs(lat)<50&&r.continent==='Oceania')return'coast';return'temperate';}
function eligible(r,night=false){const h=habitat(r),pool=catalog.filter(s=>{if(!!s.marine!==!!r.marine)return false;if(s.coast&&!r.shore)return false;if(s.when==='night'&&!night||s.when==='day'&&night)return false;if(s.countries&&!s.countries.includes(r.country))return false;if(s.key==='orangutan'){const [lon,lat]=r.anchor||r.center;if(r.country==='MYS'&&lon<108)return false;if(lon<108&&lat<-5.5)return false;}const point=s.coast?r.shore:r.anchor||r.center;if(s.box&&!inBox(point,s.box)||s.boxes&&!s.boxes.some(b=>inBox(point,b)))return false;if(s.habitats&&!s.habitats.includes(h))return false;return true;});return pool;}
const names=['Pip','River','Juniper','Moss','Cedar','Luna','Pebble','Fern','Sunny','Nori','Maple','Clover','Willow','Bramble','Cove','Sage'];
function residents(r,night=false){const pool=eligible(r,night).sort((a,b)=>Number(!!a.generic)-Number(!!b.generic)||hash(r.id+':'+a.key)-hash(r.id+':'+b.key));return pool.slice(0,3).map(s=>({...s,id:r.id+':'+s.key,name:names[hash(r.id+':'+s.key)%names.length],place:r.id,center:s.coast?r.shore:r.anchor||r.center}));}
function fresh(home){return{version:1,home,at:home,day:1,night:false,avatar:'🦝',name:'Friend',inventory:{leaf:3,wood:2,stone:2,shell:2,garland:0,lantern:0,chime:0},visited:[home],friendships:{},greeted:[],gathered:{},decor:{},invited:[],journal:['A little garden. A whole world ahead.']};}
const recipes={garland:{name:'Welcome garland',emoji:'🌼',cost:{leaf:3}},lantern:{name:'Little lantern',emoji:'🏮',cost:{wood:2,stone:1}},chime:{name:'Tide chime',emoji:'🎐',cost:{shell:2,wood:1}}};
function note(s,text){s.journal.push(text);s.journal=s.journal.slice(-60);}
function visit(s,r){s.at=r.id;if(!s.visited.includes(r.id)){s.visited.push(r.id);note(s,'Postcard: '+r.name+'.');}return r;}
function gather(s,r){if(s.at!==r.id)throw Error('Visit this place first.');if(s.gathered[r.id])throw Error('You gathered here today. A new day brings another little find.');const h=habitats[habitat(r)],item=h.items[hash(r.id+':'+s.day)%h.items.length];s.inventory[item]++;s.gathered[r.id]=true;note(s,'Found a story '+item+' in '+r.name+'.');return item;}
function greet(s,f){if(f.place!==s.at)throw Error('Visit this neighbor first.');if(s.greeted.includes(f.id))return false;s.greeted.push(f.id);s.friendships[f.id]=Math.min(5,(s.friendships[f.id]||0)+1);note(s,'Said hello to '+f.name+' the '+f.label.toLowerCase()+'.');return true;}
function craft(s,key){const r=recipes[key];if(!r)throw Error('Unknown recipe.');if(Object.entries(r.cost).some(([k,v])=>(s.inventory[k]||0)<v))throw Error('A few more materials will do it.');for(const[k,v]of Object.entries(r.cost))s.inventory[k]-=v;s.inventory[key]++;note(s,'Made a '+r.name.toLowerCase()+'.');}
function gift(s,f,key){if(f.place!==s.at)throw Error('Visit this neighbor first.');if(!recipes[key]||!s.inventory[key])throw Error('Make that gift first.');s.inventory[key]--;s.friendships[f.id]=Math.min(5,(s.friendships[f.id]||0)+2);note(s,'Gave '+f.name+' a '+recipes[key].name.toLowerCase()+'.');}
function decorate(s,key){if(!recipes[key]||!s.inventory[key])throw Error('Make that decoration first.');const list=s.decor[s.at]||(s.decor[s.at]=[]);if(list.length>=8)throw Error('This little garden has room for eight decorations.');s.inventory[key]--;list.push(key);note(s,'A '+recipes[key].name.toLowerCase()+' brightens the garden.');}
function invite(s,f){if(f.place!==s.at)throw Error('Visit this neighbor first.');if((s.friendships[f.id]||0)<3)throw Error('Three hearts unlock a home-garden invitation.');if(!s.invited.includes(f.id))s.invited.push(f.id);note(s,f.name+' accepted a story visit to your home garden.');}
function nextDay(s){s.day++;s.night=false;s.greeted=[];s.gathered={};note(s,'Day '+s.day+': another small beginning.');}
function dialogue(s,f){const level=s.friendships[f.id]||0;return level>=3?'A little kindness travels a very long way. I saved you a place beside the creek.':s.night?'The world sounds different after dark. Shall we listen for a moment?':'Welcome, traveler. Big world, small joys. What shall we make together?';}
return{catalog,source,habitats,recipes,hash,inBox,habitat,eligible,residents,fresh,visit,gather,greet,craft,gift,decorate,invite,nextDay,dialogue};});
