(function(){'use strict';
const E=WorldKings,L=CreekLesson,T=TinyWorld,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#507ba1','#b4774d','#6b8553'];let data,host,match,codes=['USA','FRA','KOR'],chosen=null,offer=null;
function save(){try{localStorage.setItem('tiny-creek-chess-v1',JSON.stringify({codes,match,chosen,offer}));}catch{host.announce('This browser could not save the chess lesson.');}}
function attempt(fn){try{fn();save();host.refresh();}catch(e){host.announce(e.message);}}
function decorate(){for(const p of match.pieces){const r=data.regions[p.at],local=[...T.eligible(r,false),...T.eligible(r,true)],pool=local.length?local:data.regions.filter(q=>q.country===r.country).flatMap(q=>T.residents(q,false));const unique=[...new Map(pool.map(f=>[f.key,f])).values()];const f=unique[T.hash(codes[p.owner]+':'+p.id)%unique.length];p.emoji=f?.emoji||'🐾';p.animal=f?.label||'Story wildlife ambassador';p.home=r.name;p.homeKind=r.kind;p.storyVisitor=!local.length;}}
function restart(){const next=[0,1,2].map(i=>$('#council-'+i).value),mode=$('#lesson-mode').value;const s=L.start(data,next,mode);match=s;codes=next;offer=null;decorate();chosen=match.pieces.find(p=>p.type==='P'&&E.legal(match,p).length)?.id??match.pieces[0].id;save();host.focusCrew(codes[0],match.pieces.filter(p=>p.owner===0).map(p=>p.at));host.announce(mode==='practice'?'Three friendly teams. Move any piece and learn together.':'A friendly council game begins. Shared peace is a shared win.');}
function selected(){return match?.pieces.find(p=>p.id===chosen);}
function moves(){const p=selected();return p&&match.phase==='play'&&(match.mode==='practice'||p.owner===match.turn)?E.legal(match,p):[];}
function selectPiece(id,focus=false){const p=match.pieces.find(p=>p.id===Number(id));if(!p)return;chosen=p.id;if(focus)host.focusRegion(p.at);else host.selectRegion(p.at);save();}
function moveTo(id){if(!selected())return;attempt(()=>{const p=selected(),from=p.at,visited=E.occupant(match,id),type=p.type;L.move(match,p.id,id,$('#promotion-role').value);host.selectRegion(p.at,false);host.announce(visited?visited.animal+' takes a safe seat on the friendship bench.':L.roles[type].name+' explored '+data.regions[p.at].name+'.');if(match.mode==='council'&&match.phase==='play')chosen=match.pieces.find(q=>q.owner===match.turn&&E.legal(match,q).length)?.id??null;});}
function chooseRegion(id){const p=E.occupant(match,id);if(p){if(moves().some(m=>m.to===id)){moveTo(id);return true;}selectPiece(p.id);return true;}if(moves().some(m=>m.to===id)){moveTo(id);return true;}return false;}
function refresh(){if(!match)return;const p=selected(),available=match.pieces.filter(q=>match.mode==='practice'||q.owner===match.turn);$('#piece-choice').innerHTML=available.map(q=>`<option value="${q.id}">${q.emoji} ${L.roles[q.type].glyph} ${L.roles[q.type].name} · ${esc(data.countries.find(c=>c.id===codes[q.owner]).name)} · ${esc(data.regions[q.at].name)}</option>`).join('');if(p&&available.some(q=>q.id===p.id))$('#piece-choice').value=p.id;
$('#chess-status').textContent=match.phase==='finished'?'🤝 Shared peace. All councils are safe.':match.mode==='practice'?'🌿 Teamwork practice · choose any friend':match.players[match.turn].name+' has the next move';$('#role-name').textContent=p?p.emoji+' '+L.roles[p.type].name:'Choose a friend';$('#role-description').textContent=p?L.roles[p.type].short:'Every team starts with sixteen pieces.';$('#site-note').textContent=p?(data.regions[p.at].kind==='garden'?'Imaginary learning garden':data.regions[p.at].kind==='city'?'Recorded city learning spot':'Mapped province or region')+' · '+data.regions[p.at].name:'';
const legal=moves();$('#move-to').innerHTML=legal.map(m=>`<option value="${m.to}">${esc(data.regions[m.to].name)}${m.capture?' · friendship bench':''}</option>`).join('');$('#move-piece').disabled=!legal.length||match.phase!=='play';$('#move-help').textContent=!p?'Select a friend to discover their routes.':legal.length?legal.length+' legal destinations. Green dots show where this friend can go.':'Other friends may block the path. Try another piece.';
$('#team-cards').innerHTML=match.players.map(player=>{const active=match.pieces.filter(q=>q.owner===player.id),rest=(match.bench||[]).filter(q=>q.owner===player.id);return `<article style="--team:${colors[player.id]}"><strong>${esc(player.name)}</strong><p>${active.length} on map · ${rest.length} resting · ${active.length+rest.length} friends</p><button data-crew="${player.id}">Visit this team ↗</button></article>`;}).join('');$('#lesson-progress').innerHTML=['P','N','B','R','Q','K'].map(type=>`<span class="lesson-badge ${match.learned?.[type]?'done':''}">${match.learned?.[type]?'✓':'○'} ${L.roles[type].glyph} ${L.roles[type].name}</span>`).join('');
$('#bench-count').textContent=match.bench?.length||0;$('#bench').innerHTML=(match.bench||[]).map(q=>`<span class="bench-friend" title="${esc(q.reason)}">${q.emoji} ${L.roles[q.type].glyph} ${L.roles[q.type].name} · ${esc(match.players[q.owner].name)}</span>`).join('')||'<p>No friends resting yet. Everyone is safe on the map.</p>';
$('#council-talk').hidden=match.mode==='practice';$('#ally-target').innerHTML=match.players.filter(q=>q.alive&&q.id!==match.turn&&!E.allied(match,q.id,match.turn)).map(q=>`<option value="${q.id}">${esc(q.name)}</option>`).join('');$('#offer-peace').disabled=match.phase!=='play'||!$('#ally-target').options.length||!!offer;$('#pending-offer').hidden=!offer;if(offer)$('#offer-text').textContent=match.players[offer.a].name+' invites '+match.players[offer.b].name+' to join their whole alliance. Pass the screen to '+match.players[offer.b].name+' to choose.';$('#council-log').innerHTML=match.log.slice(-10).reverse().map(x=>`<li>${esc(x)}</li>`).join('');}
function load(atlas,callbacks){data=atlas;host=callbacks;const options=data.countries.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');for(let i=0;i<3;i++)$('#council-'+i).innerHTML=options;
try{const saved=JSON.parse(localStorage.getItem('tiny-creek-chess-v1'));if(saved?.codes?.length===3&&new Set(saved.codes).size===3&&saved.match?.pieces?.length<=48&&saved.match.players?.length===3&&Array.isArray(saved.match.bench)&&saved.match.pieces.every(p=>data.regions[p.at]&&L.roles[p.type])&&saved.match.pieces.length+saved.match.bench.length===48){E.configure(data,saved.codes);codes=saved.codes;match=saved.match;chosen=saved.chosen;offer=saved.offer;}}catch{}
if(!match){match=L.start(data,codes,'practice');decorate();chosen=match.pieces.find(p=>p.type==='P'&&E.legal(match,p).length)?.id??match.pieces[0].id;}for(let i=0;i<3;i++)$('#council-'+i).value=codes[i];$('#lesson-mode').value=match.mode;
$('#start-councils').onclick=()=>attempt(restart);$('#piece-choice').onchange=e=>selectPiece(e.target.value,true);$('#move-piece').onclick=()=>moveTo(Number($('#move-to').value));$('#team-cards').onclick=e=>{const b=e.target.closest('[data-crew]');if(b)host.focusCrew(codes[Number(b.dataset.crew)],match.pieces.filter(p=>p.owner===Number(b.dataset.crew)).map(p=>p.at));};$('#offer-peace').onclick=()=>attempt(()=>offer=E.request(match,match.turn,Number($('#ally-target').value)));$('#accept-peace').onclick=()=>attempt(()=>{E.accept(match,offer);offer=null;});$('#decline-peace').onclick=()=>attempt(()=>{match.log.push(match.players[offer.b].name+' politely says “Not this time. We can still play kindly.”');offer=null;});refresh();save();}
function draw(ctx,p,point,size,emoji){const color=colors[p.owner];ctx.beginPath();ctx.arc(point[0],point[1],size*.82,0,Math.PI*2);ctx.fillStyle='#fffdf2d9';ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();emoji(ctx,p.emoji,point[0]-size*.32,point[1],size*.95);ctx.font=`${size*.92}px 'DejaVu Sans','Arial',sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.lineWidth=2;ctx.strokeStyle='#fffdf5';ctx.strokeText(L.roles[p.type].glyph,point[0]+size*.4,point[1]);ctx.fillStyle='#23352e';ctx.fillText(L.roles[p.type].glyph,point[0]+size*.4,point[1]);}
window.CreekChess={load,refresh,draw,selected,moves,selectPiece,chooseRegion,get match(){return match},get codes(){return codes},colors,snapshot:()=>JSON.parse(JSON.stringify({codes,match,chosen,offer}))};
})();
