(function(root,factory){const api=factory(typeof WorldKings!=='undefined'?WorldKings:require('./engine.js'));if(typeof module==='object'&&module.exports)module.exports=api;else root.CreekLesson=api;})(globalThis,function(E){
'use strict';
const roles={K:{name:'King',glyph:'♔',short:'One mapped step. In a council game, keep your king out of check.'},Q:{name:'Queen',glyph:'♕',short:'Follow straight or diagonal routes. Stop at the first occupied place.'},R:{name:'Rook',glyph:'♖',short:'Follow north, south, east, or west routes. Friends block the path.'},B:{name:'Bishop',glyph:'♗',short:'Follow diagonal routes. Friends block the path.'},N:{name:'Knight',glyph:'♘',short:'Two mapped steps in one direction, then one sideways. Jump over the middle places.'},P:{name:'Pawn',glyph:'♙',short:'One mapped step forward. Visit a rival’s occupied diagonal to send that piece safely to the bench.'}};
const stock={P:8,B:2,N:2,R:2,K:1,Q:1};
function random(seed){let x=seed>>>0;return()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296;};}
function start(data,codes,mode='practice'){if(codes.length!==3||new Set(codes).size!==3)throw Error('Choose three different countries or territories.');if(codes.some(c=>!data.countries.some(x=>x.id===c)))throw Error('Choose a place from the atlas.');E.configure(data,codes);for(let trial=0;trial<160;trial++){const s=E.fresh();s.mode=mode;if(mode==='practice')s.alliances=[0,0,0];codes.forEach((_,owner)=>E.deploy(s,owner,true,random(12039+trial*151+owner*439)));s.phase='play';if(s.players.every(p=>!E.inCheck(s,p.id)&&E.allLegal(s,p.id).length>0)){s.log.push(mode==='practice'?'A shared nature lesson begins. Every piece is a friend.':'Three councils begin a friendly chess expedition. Taken pieces rest safely on the bench.');return s;}}throw Error('Those councils need a different starting arrangement. Try another combination.');}
function counts(s,owner){return s.pieces.filter(p=>p.owner===owner).reduce((a,p)=>(a[p.type]=(a[p.type]||0)+1,a),{});}
function move(s,id,to,promotion='Q'){const p=s.pieces.find(p=>p.id===id);if(!p)throw Error('Choose a piece still on the map.');const type=p.type,result=E.move(s,id,to,promotion);s.learned={...s.learned,[type]:true};return result;}
return{roles,stock,start,counts,move};});
